import PageHeader from "../../Components/shared/PageHeader";
import MultiStepForm from "../../Components/forms/MultiStepForm ";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Form, Input, Button, Select, App, Upload, InputNumber } from "antd";
import { UploadOutlined } from "@ant-design/icons";
import { createExpert, uploadCv } from "../../services/expertService";
import { getNameList } from "country-list";
import protectedApiClient from "../../api/axios";
const { Option } = Select;

const capitalize = (s) => {
  if (typeof s !== "string" || s.length === 0) return "";
  return s.charAt(0).toUpperCase() + s.slice(1);
};

const countryOptions = Object.entries(getNameList())
  .map(([name]) => ({
    label: capitalize(name),
    value: capitalize(name),
  }))
  .sort((a, b) => a.label.localeCompare(b.label));

const subCategory = [
  { value: "Agro-industry" },
  { value: "Food" },
  { value: "Nutrition" },
  { value: "Biotechnology" },
  { value: "Credit" },
  { value: "Insurance" },
  { value: "Clearing" },
  { value: "Economics" },
  { value: "Finance" },
  { value: "Cultivation" },
  { value: "Harvesting" },
  { value: "Crop" },
  { value: "Drying" },
  { value: "Processing" },
  { value: "Scarifying" },
  { value: "Pelletizing" },
  { value: "Early Warning Systems" },
  { value: "Surveillance (Crops)" },
  { value: "Farm" },
  { value: "Co-operatives" },
  { value: "Associations" },
  { value: "Community Centres" },
  { value: "Community Participation" },
  { value: "Fisheries" },
  { value: "Aquaculture" },
  { value: "Forestry" },
  { value: "Fruits & Vegetables" },
  { value: "Horticulture" },
  { value: "Land" },
  { value: "Erosion" },
  { value: "Soil" },
  { value: "Conservation" },
  { value: "Mapping" },
  { value: "Cadastre" },
  { value: "Meat" },
  { value: "Dairy" },
  { value: "Mechanisation" },
  { value: "Production" },
  { value: "Packaging" },
  { value: "Storage" },
  { value: "Distribution" },
  { value: "Marketing" },
  { value: "Pest" },
  { value: "Disease" },
  { value: "Weed" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Systems" },
  { value: "Institutions" },
  { value: "Procurement" },
  { value: "Machinery" },
  { value: "Equipment" },
  { value: "Infrastructure" },
  { value: "Seeds" },
  { value: "Fertilisers" },
  { value: "Agro-Chemicals" },
  { value: "Pesticides" },
  { value: "Semi-arid agriculture" },
  { value: "arid agriculture" },
  { value: "Sub-tropical agriculture" },
  { value: "tropical agriculture" },
  { value: "Testing" },
  { value: "Quality Control" },
  { value: "Veterinary" },
  { value: "Water" },
  { value: "Drainage" },
  { value: "Irrigation" },
  { value: "Flood" },
  { value: "Well" },
  { value: "Hydrology" },
  { value: "Water Sanitation" },
  { value: "Zoology" },
  { value: "Livestock" },
  { value: "Animals" },
  { value: "Breeding" },
  { value: "Genetics" },
  { value: "Cattle" },
  { value: "Entomology" },
  { value: "Advertising" },
  { value: "Information Campaign" },
  { value: "Awareness-raising Campaign" },
  { value: "Communications" },
  { value: "Conferences" },
  { value: "Events" },
  { value: "Seminars" },
  { value: "Information Management" },
  { value: "Knowledge Sharing" },
  { value: "Journalism" },
  { value: "Multi-Media" },
  { value: "Printing" },
  { value: "Publishing" },
  { value: "Public Affairs" },
  { value: "Public Relations" },
  { value: "Media" },
  { value: "Radio" },
  { value: "Television" },
  { value: "Newspapers" },
  { value: "Film" },
  { value: "Photography" },
  { value: "Strategy & Policy" },
  { value: "Translation" },
  { value: "Interpretation" },
  { value: "Writing & Editing" },
  { value: "Press Release" },
  { value: "Speech" },
  { value: "Building" },
  { value: "Construction" },
  { value: "Civil Works" },
  { value: "Demolition" },
  { value: "Buildings" },
  { value: "Offices" },
  { value: "Houses" },
  { value: "Dredging & Reclamation" },
  { value: "Material" },
  { value: "Contracting" },
  { value: "Bonds" },
  { value: "Cost" },
  { value: "Highways" },
  { value: "Roads" },
  { value: "Bridges" },
  { value: "Tunnels" },
  { value: "Hydraulic Engineering (dams, pipelines, etc)" },
  { value: "Landscape Engineering" },
  { value: "Legislation" },
  { value: "Permits" },
  { value: "Standards" },
  { value: "Architecture" },
  { value: "Engineering" },
  { value: "Rehabilitation and maintenance works" },
  { value: "Site Selection" },
  { value: "Land Use" },
  { value: "Assessment" },
  { value: "Metering" },
  { value: "Protection" },
  { value: "Signalling" },
  { value: "Works supervision" },
  { value: "Comparative testing" },
  { value: "Consumer associations" },
  { value: "groups" },
  { value: "Consumer protection" },
  { value: "Consumer policy" },
  { value: "Market surveillance" },
  { value: "Consumer redress" },
  { value: "Consumer representation" },
  { value: "Contracts" },
  { value: "Contract terms" },
  { value: "Cosmetics" },
  { value: "Household appliances" },
  { value: "Cars" },
  { value: "Dangerous substances" },
  { value: "Hazardous substances" },
  { value: "Toys" },
  { value: "Information" },
  { value: "Labelling" },
  { value: "Marketing practices" },
  { value: "Sales methods" },
  { value: "Product quality control" },
  { value: "Product Safety" },
  { value: "Food Safety" },
  { value: "SPS (Sanitary / Phytosanitary)" },
  { value: "Standardisation" },
  { value: "Certification" },
  { value: "Accreditation" },
  { value: "Conformity assessment" },
  { value: "Metrology" },
  { value: "Laboratory" },
  { value: "Sustainable consumption" },
  { value: "Warnings" },
  { value: "Warranty" },
  { value: "Business Centres" },
  { value: "Incubators" },
  { value: "Business Development" },
  { value: "Business Plans" },
  { value: "Clustering" },
  { value: "Co-operatives" },
  { value: "Corporate Governance" },
  { value: "Econometrics" },
  { value: "Statistics" },
  { value: "Income Distribution" },
  { value: "Economic Systems" },
  { value: "Planning" },
  { value: "Employment" },
  { value: "Labour" },
  { value: "Handicraft" },
  { value: "Household" },
  { value: "Income Generation" },
  { value: "Macroeconomics" },
  { value: "Crisis" },
  { value: "Matching Grants" },
  { value: "Mergers & Acquisitions" },
  { value: "Partnerships" },
  { value: "Joint Ventures" },
  { value: "Micro-Credit" },
  { value: "Microeconomics" },
  { value: "Privatisation" },
  { value: "Public-Private Partnership" },
  { value: "Re-engineering (company)" },
  { value: "Liquidation" },
  { value: "Restructuring (sector" },
  { value: "industry)" },
  { value: "Small & Medium-Sized Enterprises (SMEs)" },
  { value: "Start-ups" },
  { value: "Tourism" },
  { value: "Hotels" },
  { value: "Restaurants" },
  { value: "Catering" },
  { value: "Adult Education" },
  { value: "Non-Formal" },
  { value: "Literacy" },
  { value: "Continuing" },
  { value: "Curriculum" },
  { value: "Distance Education" },
  { value: "e-Learning" },
  { value: "Education Technology" },
  { value: "Exchange" },
  { value: "Scholarship" },
  { value: "Facilities" },
  { value: "Architecture" },
  { value: "Physical Planning" },
  { value: "Location" },
  { value: "Finance" },
  { value: "Accounting" },
  { value: "Audit" },
  { value: "Higher" },
  { value: "University" },
  { value: "Library" },
  { value: "Documentation Centre" },
  { value: "Manpower" },
  { value: "Personnel" },
  { value: "Marginalised groups" },
  { value: "Handicapped" },
  { value: "Girls & Women" },
  { value: "School attendance" },
  { value: "Performance" },
  { value: "Examinations" },
  { value: "Testing" },
  { value: "Measurement" },
  { value: "Inspectorate" },
  { value: "Supervision" },
  { value: "National Qualification framework (NQF)" },
  { value: "Policy" },
  { value: "Systems" },
  { value: "Institutions" },
  { value: "Evaluation" },
  { value: "Decentralisation" },
  { value: "Pre-School" },
  { value: "Early Childhood" },
  { value: "Primary" },
  { value: "Procurement" },
  { value: "Equipment" },
  { value: "Materials" },
  { value: "Media" },
  { value: "Techniques" },
  { value: "Textbooks" },
  { value: "Publishing" },
  { value: "Radio & Television" },
  { value: "Research & Development" },
  { value: "Secondary" },
  { value: "Teachers Training" },
  { value: "Technical" },
  { value: "Industrial" },
  { value: "Vocational" },
  { value: "Tertiary" },
  { value: "Conservation" },
  { value: "Saving" },
  { value: "Recovery" },
  { value: "Renewable" },
  { value: "Drilling" },
  { value: "Production" },
  { value: "Distribution" },
  { value: "Reserves" },
  { value: "Electric" },
  { value: "Financials" },
  { value: "Pricing" },
  { value: "Tariffs" },
  { value: "Geothermal" },
  { value: "Solar" },
  { value: "Bio-Mass" },
  { value: "Wind" },
  { value: "Sea" },
  { value: "Heating" },
  { value: "Co-Generation" },
  { value: "Hydroelectric" },
  { value: "Mining" },
  { value: "Coal" },
  { value: "Lignite" },
  { value: "Anthracite" },
  { value: "Nuclear" },
  { value: "Oil" },
  { value: "Gas" },
  { value: "Petrol" },
  { value: "Planning" },
  { value: "Policy" },
  { value: "Procurement" },
  { value: "Equipment" },
  { value: "Bio-diversity" },
  { value: "Eco Systems" },
  { value: "Botany" },
  { value: "Climate" },
  { value: "Cyclone" },
  { value: "Coastal Zone Management" },
  { value: "Marine Biology" },
  { value: "Drought & Desertification" },
  { value: "Environmental Engineering" },
  { value: "Science & Technology" },
  { value: "Historic & Cultural Heritage" },
  { value: "Natural disasters" },
  { value: "Prevention" },
  { value: "Natural resources" },
  { value: "Earth & Space sciences" },
  { value: "Ecology" },
  { value: "Policy & Strategy (incl. Sustainability)" },
  { value: "Pollution (Air)" },
  { value: "Pollution (Water)" },
  { value: "Pollution (Soil)" },
  { value: "Pollution (Noise)" },
  { value: "Pollution (Industrial)" },
  { value: "Pollution (Oil)" },
  { value: "Protected Areas" },
  { value: "Parks" },
  { value: "Reserves" },
  { value: "Protection" },
  { value: "Bio-economy" },
  { value: "Green economy" },
  { value: "Remote Sensing" },
  { value: "Early Warning Systems" },
  { value: "Surveillance" },
  { value: "Standards" },
  { value: "Surveys" },
  { value: "Impact Assessment" },
  { value: "Topography" },
  { value: "Geology" },
  { value: "Earth Observation" },
  { value: "Urban Environment" },
  { value: "Waste" },
  { value: "Toxic" },
  { value: "Hazardous" },
  { value: "Solid" },
  { value: "Clean Technologies" },
  { value: "Processing" },
  { value: "Wildlife" },
  { value: "Audit" },
  { value: "Accountancy" },
  { value: "Due Diligence" },
  { value: "Inventory" },
  { value: "Balance of Payments" },
  { value: "Banking system" },
  { value: "Budgets" },
  { value: "Public Finance" },
  { value: "Capital" },
  { value: "Reserves" },
  { value: "Liquidity" },
  { value: "Cash Flow" },
  { value: "Liability" },
  { value: "Creditors" },
  { value: "Treasury" },
  { value: "Co-financing" },
  { value: "Corporate finance" },
  { value: "Credit" },
  { value: "Letters of Credit" },
  { value: "Loans" },
  { value: "Credit Guarantees" },
  { value: "Currency" },
  { value: "Exchange" },
  { value: "Debt" },
  { value: "Indebtedness" },
  { value: "Financial Institutions" },
  { value: "Insurance" },
  { value: "Investment" },
  { value: "Venture capital" },
  { value: "Portfolio" },
  { value: "Securities" },
  { value: "Bonds" },
  { value: "Stocks" },
  { value: "Equities" },
  { value: "Funds" },
  { value: "Leasing" },
  { value: "Market Instruments" },
  { value: "Derivatives" },
  { value: "Financial Markets" },
  { value: "Exchanges" },
  { value: "Monetary" },
  { value: "Fiscal Policy" },
  { value: "Money laundering" },
  { value: "Fraud" },
  { value: "Payments" },
  { value: "Mobile Banking" },
  { value: "E-Banking" },
  { value: "Pensions" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Systems" },
  { value: "Regulations" },
  { value: "Crisis" },
  { value: "Reporting" },
  { value: "Finance Management" },
  { value: "Risk" },
  { value: "Sensitivity" },
  { value: "Market analysis" },
  { value: "Forecasting" },
  { value: "Models" },
  { value: "Projection" },
  { value: "Structural Adjustment" },
  { value: "Taxation" },
  { value: "Collection" },
  { value: "Bio-Medicine" },
  { value: "Diseases" },
  { value: "Vaccination" },
  { value: "Epidemic" },
  { value: "Prevention" },
  { value: "Risks" },
  { value: "Economics & Finances" },
  { value: "Health Insurance" },
  { value: "Genetics" },
  { value: "Health Care Buildings" },
  { value: "Hospital" },
  { value: "HIV" },
  { value: "AIDS" },
  { value: "STD" },
  { value: "Manpower" },
  { value: "Maternal-Child health" },
  { value: "Maternity" },
  { value: "Family planning" },
  { value: "Reproductive health" },
  { value: "Nursing" },
  { value: "Mental Health" },
  { value: "Disabled" },
  { value: "Nutrition" },
  { value: "Occupational Health" },
  { value: "Patients' rights" },
  { value: "Protection" },
  { value: "Pharmaceuticals" },
  { value: "Drugs" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Systems" },
  { value: "Organisation" },
  { value: "Administration" },
  { value: "Management" },
  { value: "e-Health" },
  { value: "Primary Health Care" },
  { value: "Private Health Care Systems" },
  { value: "Infrastructure" },
  { value: "Procurement" },
  { value: "Logistics" },
  { value: "Equipment" },
  { value: "Supplies" },
  { value: "Distribution" },
  { value: "Delivery" },
  { value: "Public Health Care Systems" },
  { value: "Districts" },
  { value: "Research" },
  { value: "Safety" },
  { value: "Liability" },
  { value: "Sanitation" },
  { value: "Food Aid" },
  { value: "Land Mines" },
  { value: "Mine Clearance" },
  { value: "Medical Aid" },
  { value: "Prevention" },
  { value: "Preparedness" },
  { value: "Refugees" },
  { value: "Returnees" },
  { value: "Displaced" },
  { value: "Temporary Shelters" },
  { value: "Artificial intelligence" },
  { value: "Automation" },
  { value: "Computer Networks" },
  { value: "Operations" },
  { value: "Maintenance and Support" },
  { value: "Security" },
  { value: "Computer-Assisted Design (CAD/CAM)" },
  { value: "Databases" },
  { value: "Warehouses" },
  { value: "Data Recovery" },
  { value: "Decision Support Systems" },
  { value: "Geographical Information" },
  { value: "Localisation" },
  { value: "Surveillance Systems" },
  { value: "Hardware" },
  { value: "Software" },
  { value: "Information society" },
  { value: "Internet" },
  { value: "Web-based Platforms" },
  { value: "e-Commerce" },
  { value: "e-Governance" },
  { value: "Management Information Systems (MIS)" },
  { value: "Teletext" },
  { value: "Web Design" },
  { value: "Administrative Law" },
  { value: "Anti-corruption" },
  { value: "Bankruptcy" },
  { value: "Creditors Rights" },
  { value: "Insolvency" },
  { value: "Civil law" },
  { value: "Public law" },
  { value: "Election law" },
  { value: "Political Party Law" },
  { value: "Commercial Law" },
  { value: "Trade Law" },
  { value: "Contract Law" },
  { value: "Corporate Law" },
  { value: "Industrial Law" },
  { value: "Economic Law" },
  { value: "Competition Law" },
  { value: "Computer Law" },
  { value: "e-Commerce Law" },
  { value: "Internet Law" },
  { value: "Constitutional Law" },
  { value: "Courts" },
  { value: "Tribunals" },
  { value: "Law Enforcement" },
  { value: "Justice" },
  { value: "Criminal Law" },
  { value: "Environmental Law" },
  { value: "Energy Law" },
  { value: "Financial Law" },
  { value: "Banking Law" },
  { value: "Investment Law" },
  { value: "Governmental Law" },
  { value: "Human Rights Protection Law" },
  { value: "Immigration Law" },
  { value: "Insurance Law" },
  { value: "International Law" },
  { value: "Judges" },
  { value: "Labour Law" },
  { value: "Law" },
  { value: "Legislation" },
  { value: "Legal Framework" },
  { value: "Regulation" },
  { value: "RIA" },
  { value: "Reform" },
  { value: "Law Harmonisation" },
  { value: "Approximation" },
  { value: "Pre-accession" },
  { value: "Acquis communautaire" },
  { value: "European Law" },
  { value: "Patent" },
  { value: "Trademark" },
  { value: "Copyright" },
  { value: "Intellectual Property" },
  { value: "Property" },
  { value: "Estates" },
  { value: "Trusts" },
  { value: "Secured Transactions" },
  { value: "Privacy" },
  { value: "Data protection" },
  { value: "Securities" },
  { value: "State Enterprises Law" },
  { value: "Taxation" },
  { value: "Income" },
  { value: "Chartered Surveyors" },
  { value: "Torts" },
  { value: "Dispute Settlement" },
  { value: "Dialogue" },
  { value: "Arbitration" },
  { value: "Litigation" },
  { value: "Mediation" },
  { value: "Transport Law" },
  { value: "Co-ordination" },
  { value: "Aid co-ordination" },
  { value: "Cost Analysis" },
  { value: "Benefits Analysis" },
  { value: "Project Budgeting" },
  { value: "Country Programming" },
  { value: "Programme Development" },
  { value: "Identification" },
  { value: "Needs Analysis" },
  { value: "Formulation" },
  { value: "Feasibility Study" },
  { value: "Management Systems & Techniques" },
  { value: "Monitoring" },
  { value: "Evaluation" },
  { value: "Assessment" },
  { value: "(impact) Studies" },
  { value: "Project Audit" },
  { value: "Survey" },
  { value: "Performance Appraisal" },
  { value: "Personnel" },
  { value: "Human Resources Management" },
  { value: "Procurement" },
  { value: "Tender evaluation" },
  { value: "Project Cycle Management" },
  { value: "Project implementation" },
  { value: "Secretarial Support" },
  { value: "Administrative Support" },
  { value: "Total Quality Management (TQM)" },
  { value: "Quality Control" },
  { value: "Training" },
  { value: "Administrative Agencies" },
  { value: "Budget" },
  { value: "Budget Support" },
  { value: "Public Investment" },
  { value: "Finances" },
  { value: "Debt" },
  { value: "Customs" },
  { value: "Excise" },
  { value: "Elections" },
  { value: "Polling" },
  { value: "Voters" },
  { value: "Fight against drugs" },
  { value: "Foreign Affairs" },
  { value: "Diplomacy" },
  { value: "Governance" },
  { value: "Justice and Home Affairs" },
  { value: "Asylum" },
  { value: "Immigration" },
  { value: "Borders" },
  { value: "Passport" },
  { value: "Manpower" },
  { value: "Recruitment" },
  { value: "HR" },
  { value: "Grading" },
  { value: "Parliament" },
  { value: "Political Parties" },
  { value: "Planning" },
  { value: "Policy" },
  { value: "Systems" },
  { value: "Police" },
  { value: "Defence" },
  { value: "Interior" },
  { value: "Security" },
  { value: "Prison" },
  { value: "Fire fighting system" },
  { value: "Public Procurement" },
  { value: "Public utilities" },
  { value: "Institutional strengthening" },
  { value: "Regional Authorities" },
  { value: "Municipal Authorities" },
  { value: "Local Authorities" },
  { value: "Decentralisation" },
  { value: "Regional Country Co-operation" },
  { value: "European Integration" },
  { value: "Regional Funds" },
  { value: "State Enterprises" },
  { value: "Terrorism" },
  { value: "Corruption" },
  { value: "Fight against human traffic" },
  { value: "Twinning" },
  { value: "Chemistry" },
  { value: "Earth sciences" },
  { value: "Human Sciences" },
  { value: "Information Sciences" },
  { value: "Life and Health Sciences" },
  { value: "Other Sciences" },
  { value: "Physics" },
  { value: "Procurement" },
  { value: "Equipment" },
  { value: "Anthropology" },
  { value: "Tribal" },
  { value: "Ethnic Groups" },
  { value: "Classification" },
  { value: "Norms" },
  { value: "Standards" },
  { value: "Conflict" },
  { value: "Post conflict" },
  { value: "Conflict prevention" },
  { value: "Political crises" },
  { value: "Culture" },
  { value: "Religion" },
  { value: "Sport" },
  { value: "Arts" },
  { value: "Democracy" },
  { value: "Human Rights" },
  { value: "Family Planning" },
  { value: "Gender" },
  { value: "Women" },
  { value: "Equal Opportunities" },
  { value: "Discrimination" },
  { value: "Re-integration" },
  { value: "Migration" },
  { value: "Settlement" },
  { value: "Resettlement" },
  { value: "Border Crossing" },
  { value: "Pastoral Groups" },
  { value: "Nomads" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Systems" },
  { value: "Reform" },
  { value: "Poverty Alleviation" },
  { value: "Vehicles" },
  { value: "Supplies" },
  { value: "Facilities" },
  { value: "Rent" },
  { value: "Self-help" },
  { value: "Grass-roots" },
  { value: "Social Security" },
  { value: "Pension" },
  { value: "Protection" },
  { value: "Statistics" },
  { value: "Demography" },
  { value: "Population" },
  { value: "Census" },
  { value: "Opinion Polling" },
  { value: "Research" },
  { value: "Volunteering" },
  { value: "NGO" },
  { value: "CBO" },
  { value: "Trade Unions" },
  { value: "Civil Society" },
  { value: "Vulnerable Groups" },
  { value: "Street Children" },
  { value: "Minorities" },
  { value: "Youth" },
  { value: "Mobile systems" },
  { value: "Services" },
  { value: "Post" },
  { value: "Courier service" },
  { value: "Teletext" },
  { value: "Tariffs" },
  { value: "Chambers of Commerce" },
  { value: "Commodities" },
  { value: "Raw Materials" },
  { value: "Export" },
  { value: "Competition" },
  { value: "Foreign Direct Investments" },
  { value: "Investment promotion" },
  { value: "Free Trade Zones" },
  { value: "Industrial Parks" },
  { value: "Estates" },
  { value: "Import" },
  { value: "Industry" },
  { value: "Industrial Products" },
  { value: "Licencing" },
  { value: "Patents" },
  { value: "Trademarks" },
  { value: "Logistics" },
  { value: "Market Analysis" },
  { value: "Market Surveillance" },
  { value: "Marketing" },
  { value: "Direct Marketing" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Pricing" },
  { value: "Procurement" },
  { value: "Purchasing & Supply" },
  { value: "Sales" },
  { value: "Promotion" },
  { value: "Aids" },
  { value: "Facilitation" },
  { value: "Retail Management" },
  { value: "Sponsorship" },
  { value: "Tariff" },
  { value: "Barriers" },
  { value: "Contracts" },
  { value: "Terms" },
  { value: "Restrictions" },
  { value: "Trade" },
  { value: "Global trade" },
  { value: "Air" },
  { value: "Aviation" },
  { value: "Airport" },
  { value: "Freight" },
  { value: "Cargo" },
  { value: "Inter-modal" },
  { value: "Multi-modal" },
  { value: "Investment" },
  { value: "Finances" },
  { value: "Navigational Aids" },
  { value: "Models" },
  { value: "Equipment" },
  { value: "Vehicles" },
  { value: "Maintenance" },
  { value: "Rail" },
  { value: "Regulation" },
  { value: "Road" },
  { value: "Public transportation" },
  { value: "Safety" },
  { value: "Traffic" },
  { value: "Origin-Destination Surveys" },
  { value: "Warehouses" },
  { value: "Storage" },
  { value: "Water Navigation" },
  { value: "Ports" },
  { value: "Shipping" },
  { value: "Food Aid" },
  { value: "Land Mines" },
  { value: "Mine Clearance" },
  { value: "Medical Aid" },
  { value: "Prevention" },
  { value: "Preparedness" },
  { value: "Refugees" },
  { value: "Returnees" },
  { value: "Displaced" },
  { value: "Temporary Shelters" },
  { value: "Community Participation" },
  { value: "Employment" },
  { value: "Energy" },
  { value: "Engineering" },
  { value: "Infrastructure" },
  { value: "Implementation" },
  { value: "Building" },
  { value: "Works Supervision" },
  { value: "Finance" },
  { value: "Budgeting" },
  { value: "Investment" },
  { value: "Valuation" },
  { value: "Taxation" },
  { value: "Land Use" },
  { value: "Pedestrian" },
  { value: "Planning" },
  { value: "Models" },
  { value: "Policies" },
  { value: "Property" },
  { value: "Facilities" },
  { value: "Asset Management" },
  { value: "Public utilities" },
  { value: "Self-help Programmes" },
  { value: "Services" },
  { value: "Maintenance" },
  { value: "Cleaning services" },
  { value: "Shelter" },
  { value: "Housing" },
  { value: "Habitat" },
  { value: "Slums" },
  { value: "Standards & Regulations" },
  { value: "Survey" },
  { value: "Transport" },
  { value: "Water" },
  { value: "Drainage" },
  { value: "Irrigation" },
  { value: "Flood" },
  { value: "Well" },
  { value: "Hydrology" },
];
const nationalitys = [
  { value: "Afghan", label: "Afghan" },
  { value: "Albanian", label: "Albanian" },
  { value: "Algerian", label: "Algerian" },
  { value: "American", label: "American" },
  { value: "Andorran", label: "Andorran" },
  { value: "Angolan", label: "Angolan" },
  { value: "Antiguan", label: "Antiguan" },
  { value: "Argentine", label: "Argentine" },
  { value: "Armenian", label: "Armenian" },
  { value: "Australian", label: "Australian" },
  { value: "Austrian", label: "Austrian" },
  { value: "Azerbaijani", label: "Azerbaijani" },
  { value: "Bahamian", label: "Bahamian" },
  { value: "Bahraini", label: "Bahraini" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Barbadian", label: "Barbadian" },
  { value: "Basotho", label: "Basotho" },
  { value: "Belarusian", label: "Belarusian" },
  { value: "Belgian", label: "Belgian" },
  { value: "Belizean", label: "Belizean" },
  { value: "Beninese", label: "Beninese" },
  { value: "Bhutanese", label: "Bhutanese" },
  { value: "Bolivian", label: "Bolivian" },
  { value: "Bosnian", label: "Bosnian" },
  { value: "Botswanan", label: "Botswanan" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "British", label: "British" },
  { value: "Bruneian", label: "Bruneian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Burkinabé", label: "Burkinabé" },
  { value: "Burmese", label: "Burmese" },
  { value: "Burundian", label: "Burundian" },
  { value: "Cabo Verdean", label: "Cabo Verdean" },
  { value: "Cambodian", label: "Cambodian" },
  { value: "Cameroonian", label: "Cameroonian" },
  { value: "Canadian", label: "Canadian" },
  { value: "Central African", label: "Central African" },
  { value: "Chadian", label: "Chadian" },
  { value: "Chilean", label: "Chilean" },
  { value: "Chinese", label: "Chinese" },
  { value: "Colombian", label: "Colombian" },
  { value: "Comoran", label: "Comoran" },
  { value: "Congolese", label: "Congolese" },
  { value: "Costa Rican", label: "Costa Rican" },
  { value: "Croatian", label: "Croatian" },
  { value: "Cuban", label: "Cuban" },
  { value: "Cypriot", label: "Cypriot" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Djiboutian", label: "Djiboutian" },
  { value: "Dominican", label: "Dominican" },
  { value: "Dutch", label: "Dutch" },
  { value: "East Timorese", label: "East Timorese" },
  { value: "Ecuadorian", label: "Ecuadorian" },
  { value: "Egyptian", label: "Egyptian" },
  { value: "Emirati", label: "Emirati" },
  { value: "English", label: "English" },
  { value: "Equatoguinean", label: "Equatoguinean" },
  { value: "Eritrean", label: "Eritrean" },
  { value: "Estonian", label: "Estonian" },
  { value: "Ethiopian", label: "Ethiopian" },
  { value: "Fijian", label: "Fijian" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },
  { value: "Gabonese", label: "Gabonese" },
  { value: "Gambian", label: "Gambian" },
  { value: "Georgian", label: "Georgian" },
  { value: "German", label: "German" },
  { value: "Ghanaian", label: "Ghanaian" },
  { value: "Greek", label: "Greek" },
  { value: "Grenadian", label: "Grenadian" },
  { value: "Guatemalan", label: "Guatemalan" },
  { value: "Guinean", label: "Guinean" },
  { value: "Bissau-Guinean", label: "Bissau-Guinean" },
  { value: "Guyanese", label: "Guyanese" },
  { value: "Haitian", label: "Haitian" },
  { value: "Honduran", label: "Honduran" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "Icelander", label: "Icelander" },
  { value: "Indian", label: "Indian" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Iranian", label: "Iranian" },
  { value: "Iraqi", label: "Iraqi" },
  { value: "Irish", label: "Irish" },
  { value: "Israeli", label: "Israeli" },
  { value: "Italian", label: "Italian" },
  { value: "Ivorian", label: "Ivorian" },
  { value: "Jamaican", label: "Jamaican" },
  { value: "Japanese", label: "Japanese" },
  { value: "Jordanian", label: "Jordanian" },
  { value: "Kazakhstani", label: "Kazakhstani" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "Kittitian", label: "Kittitian" },
  { value: "Kosovar", label: "Kosovar" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Kyrgyzstani", label: "Kyrgyzstani" },
  { value: "Lao", label: "Lao" },
  { value: "Latvian", label: "Latvian" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Liberian", label: "Liberian" },
  { value: "Libyan", label: "Libyan" },
  { value: "Liechtensteiner", label: "Liechtensteiner" },
  { value: "Lithuanian", label: "Lithuanian" },
  { value: "Luxembourger", label: "Luxembourger" },
  { value: "Macedonian", label: "Macedonian" },
  { value: "Malagasy", label: "Malagasy" },
  { value: "Malawian", label: "Malawian" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Maldivian", label: "Maldivian" },
  { value: "Malian", label: "Malian" },
  { value: "Maltese", label: "Maltese" },
  { value: "Marshallese", label: "Marshallese" },
  { value: "Mauritanian", label: "Mauritanian" },
  { value: "Mauritian", label: "Mauritian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Micronesian", label: "Micronesian" },
  { value: "Moldovan", label: "Moldovan" },
  { value: "Monacan", label: "Monacan" },
  { value: "Mongolian", label: "Mongolian" },
  { value: "Montenegrin", label: "Montenegrin" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Mozambican", label: "Mozambican" },
  { value: "Namibian", label: "Namibian" },
  { value: "Nauruan", label: "Nauruan" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "New Zealander", label: "New Zealander" },
  { value: "Nicaraguan", label: "Nicaraguan" },
  { value: "Nigerien", label: "Nigerien" },
  { value: "Nigerian", label: "Nigerian" },
  { value: "Ni-Vanuatu", label: "Ni-Vanuatu" },
  { value: "North Korean", label: "North Korean" },
  { value: "Norwegian", label: "Norwegian" },
  { value: "Omani", label: "Omani" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Palauan", label: "Palauan" },
  { value: "Palestinian", label: "Palestinian" },
  { value: "Panamanian", label: "Panamanian" },
  { value: "Papua New Guinean", label: "Papua New Guinean" },
  { value: "Paraguayan", label: "Paraguayan" },
  { value: "Peruvian", label: "Peruvian" },
  { value: "Filipino", label: "Filipino" },
  { value: "Polish", label: "Polish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Qatari", label: "Qatari" },
  { value: "Romanian", label: "Romanian" },
  { value: "Russian", label: "Russian" },
  { value: "Rwandan", label: "Rwandan" },
  { value: "Saint Lucian", label: "Saint Lucian" },
  { value: "Salvadoran", label: "Salvadoran" },
  { value: "Sammarinese", label: "Sammarinese" },
  { value: "Samoan", label: "Samoan" },
  { value: "São Toméan", label: "São Toméan" },
  { value: "Saudi", label: "Saudi" },
  { value: "Scottish", label: "Scottish" },
  { value: "Senegalese", label: "Senegalese" },
  { value: "Serbian", label: "Serbian" },
  { value: "Seychellois", label: "Seychellois" },
  { value: "Sierra Leonean", label: "Sierra Leonean" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "Slovak", label: "Slovak" },
  { value: "Slovene", label: "Slovene" },
  { value: "Solomon Islander", label: "Solomon Islander" },
  { value: "Somali", label: "Somali" },
  { value: "South African", label: "South African" },
  { value: "South Korean", label: "South Korean" },
  { value: "South Sudanese", label: "South Sudanese" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Sudanese", label: "Sudanese" },
  { value: "Surinamese", label: "Surinamese" },
  { value: "Swazi", label: "Swazi" },
  { value: "Swedish", label: "Swedish" },
  { value: "Swiss", label: "Swiss" },
  { value: "Syrian", label: "Syrian" },
  { value: "Tajikistani", label: "Tajikistani" },
  { value: "Tanzanian", label: "Tanzanian" },
  { value: "Thai", label: "Thai" },
  { value: "Togolese", label: "Togolese" },
  { value: "Tongan", label: "Tongan" },
  { value: "Trinidadian", label: "Trinidadian" },
  { value: "Tunisian", label: "Tunisian" },
  { value: "Turkish", label: "Turkish" },
  { value: "Turkmen", label: "Turkmen" },
  { value: "Tuvaluan", label: "Tuvaluan" },
  { value: "Ugandan", label: "Ugandan" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Uruguayan", label: "Uruguayan" },
  { value: "Uzbekistani", label: "Uzbekistani" },
  { value: "Vatican", label: "Vatican" },
  { value: "Venezuelan", label: "Venezuelan" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Vincentian", label: "Vincentian" },
  { value: "Welsh", label: "Welsh" },
  { value: "Yemeni", label: "Yemeni" },
  { value: "Zambian", label: "Zambian" },
  { value: "Zimbabwean", label: "Zimbabwean" },
];

const QuickUploadPage = () => {
  const navigate = useNavigate();
  const { message } = App.useApp();
  const [form] = Form.useForm();
  const [createdExpertId, setCreatedExpertId] = useState(null);
  const [isStep1Submitting, setIsStep1Submitting] = useState(false);
  const [isFinalSubmitting, setIsFinalSubmitting] = useState(false);
  const userId = localStorage.getItem("userId");
  const [formated, setFormated] = useState(true);

  const sortedSubCategory = subCategory
    .filter(
      (item, index, self) =>
        index ===
        self.findIndex(
          (t) => t.value.toLowerCase() === item.value.toLowerCase()
        )
    )
    .sort((a, b) => a.value.toLowerCase().localeCompare(b.value.toLowerCase()));

  // Sort alphabetically
  // const sortedSubCategory = uniqueSubCategory.sort((a, b) =>
  //   a.value.toLowerCase().localeCompare(b.value.toLowerCase())
  // );

  const steps = [
    {
      title: "Personal Detail",
      fields: [
        "firstName",
        "lastName",
        "country",
        "cv_language",
        "email",
        "expertise_area",
        "year_of_experience",
      ],
      content: (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 mt-5">
            <Form.Item
              label="First Name"
              name="firstName"
              rules={[{ required: true }]}
            >
              <Input placeholder="Enter first name" size="large" />
            </Form.Item>
            <Form.Item
              label="Last Name"
              name="lastName"
              rules={[{ required: true }]}
            >
              <Input placeholder="Enter last name" size="large" />
            </Form.Item>
            <Form.Item label="Nationality" name="nationality">
              <Select
                size="large"
                allowClear
                showSearch
                filterOption={(input, option) =>
                  (option?.label ?? "")
                    .toLowerCase()
                    .includes(input.toLowerCase())
                }
                options={nationalitys}
              />
            </Form.Item>
            <Form.Item label="CV Language" name="cv_language">
              <Select placeholder="Select language" size="large">
                <Option value="English">English</Option>
                <Option value="Amharic">Amharic</Option>
              </Select>
            </Form.Item>
            <Form.Item
              label="Email Address"
              name="email"
              rules={[{ required: true, type: "email" }]}
            >
              <Input placeholder="example@email.com" size="large" />
            </Form.Item>
            <Form.Item
              label="Area of Expertise"
              name="expertise_area"
              rules={[
                {
                  required: true,
                  message: "Please enter at least one expertise area.",
                },
              ]}
            >
              <Select
                mode="multiple"
                options={sortedSubCategory}
                placeholder="Type and press Enter to add expertise areas"
                size="large"
              />
            </Form.Item>
            <Form.Item
              label="Years of Experience"
              name="year_of_experience"
              rules={[
                { required: true, message: "Please enter years of experience" },
              ]}
            >
              <InputNumber
                min={0}
                max={50}
                placeholder="e.g., 10"
                style={{ width: "100%" }}
                size="large"
              />
            </Form.Item>
          </div>
        </>
      ),
    },
    {
      title: "CV Upload",
      fields: ["cv_file"],
      content: (
        <>
          <p className="dashboard-meta text-center mb-4">
            Please upload the expert's CV file. Accepted formats: PDF, DOC,
            DOCX.
          </p>
          <div className="flex gap-3 my-4 mt-8">
            <button
              onClick={() => setFormated(true)}
              className={`dashboard-btn-ghost ${
                formated ? "!bg-[var(--color-primary)] !text-white !border-[var(--color-primary)]" : ""
              }`}
            >
              Formatted
            </button>
            <button
              onClick={() => setFormated(false)}
              className={`dashboard-btn-ghost ${
                !formated ? "!bg-[var(--color-primary)] !text-white !border-[var(--color-primary)]" : ""
              }`}
            >
              Unformatted
            </button>
          </div>
          <Form.Item
            label="Upload CV"
            name="cv_file"
            valuePropName="fileList"
            getValueFromEvent={(e) => (Array.isArray(e) ? e : e?.fileList)}
            rules={[{ required: true, message: "Please upload a CV file" }]}
          >
            <Upload name="cv" beforeUpload={() => false} maxCount={1}>
              <Button icon={<UploadOutlined />}>Click to Upload CV</Button>
            </Upload>
          </Form.Item>
        </>
      ),
    },
  ];
  const handleStep1Next = async (values) => {
    const expertiseArray = values.expertise_area || [];
    const expertiseString = expertiseArray.join(", ");
    const personalInfo = {
      first_name: values.firstName,
      last_name: values.lastName,
      email: values.email,
      expertise_area: expertiseString,
      nationality: values.nationality,
      cv_language: values.cv_language,
      year_of_experience: values.year_of_experience,
      registered_by: userId,
    };

    setIsStep1Submitting(true);
    message.loading({ content: "Creating expert profile...", key: "step1" });

    try {
      const createResponse = await createExpert(personalInfo);
      message.destroy("step1");
      message.success("Expert profile created. Please upload the CV.");

      setCreatedExpertId(createResponse.id);
      setIsStep1Submitting(false);
      return true;
    } catch (error) {
      message.destroy("step1");
      setIsStep1Submitting(false);
      const errorMessage =
        error.response?.data?.email?.[0] || "Failed to create expert.";
      message.error(errorMessage);
      return false;
    }
  };

  const handleFinalSubmit = async (values) => {
    if (!createdExpertId) {
      message.error(
        "Could not upload CV because the expert was not created first. Please go back."
      );
      return;
    }
    // setIsFinalSubmitting(true);
    message.loading({ content: "Uploading CV...", key: "finalSubmit" });

    try {
      const cvFile = values.cv_file[0].originFileObj;
      const cvFormData = new FormData();
      cvFormData.append("cv_file", cvFile);
      cvFormData.append("expert_id", createdExpertId);

      if (!formated) {
        console.log();
        // const createResponse = await createExpert(cvFormData);
        const response = await protectedApiClient.patch(
          `/api/v1/experts/${createdExpertId}/`,
          cvFormData,
          {
            headers: {
              "Content-Type": "multipart/form-data",
            },
          }
        );
      } else {
        await uploadCv(cvFormData);
      }

      message.destroy("finalSubmit");
      message.success("Expert and CV registered successfully!");
      navigate("/dashboard/all");
    } catch (error) {
      message.destroy("finalSubmit");
      message.error(
        "The CV upload failed. Please try again or upload it manually later."
      );
      console.error("CV Upload failed:", error);
    } finally {
      setIsFinalSubmitting(false);
    }
  };
  return (
    <div className="dashboard-container">
      <div className="dashboard-main-content">
        <PageHeader title="Register New Expert" description="Follow the steps below to quickly add a new expert by uploading their CV." />
        
        <div className="dashboard-card flex-1 flex flex-col">
          <MultiStepForm
            form={form}
            steps={steps}
            onSubmit={handleFinalSubmit}
            onStep1Next={handleStep1Next}
            isStep1Submitting={isStep1Submitting}
            isSubmitting={isFinalSubmitting}
            submitButtonText="Register"
          />
        </div>
      </div>
    </div>
  );
};

export default QuickUploadPage;
