/* ============================================================
   searchTaxonomy.js — shared sector / geography / funding data

   Extracted from AdvancedSearchForm so the search workspace and
   the legacy form read one source instead of two copies.
   ============================================================ */

import { getNameList } from "country-list";

export const sectorsData = [
  {
    category: "Ag. & Rural Dev.",
    subCategories: [
      "Agro-industry / Food / Nutrition",
      "Biotechnology",
      "Credit / Insurance / Clearing / Economics / Finance",
      "Cultivation / Harvesting / Crop",
      "Drying / Processing / Scarifying / Pelletizing",
      "Early Warning Systems / Surveillance (Crops)",
      "Farm / Co-operatives / Associations / Community Centres / Community Participation",
      "Fisheries / Aquaculture",
      "Forestry",
      "Fruits & Vegetables",
      "Horticulture",
      "Land / Erosion / Soil / Conservation",
      "Mapping / Cadastre",
      "Meat & Dairy",
      "Mechanisation / Production",
      "Packaging / Storage / Distribution / Marketing",
      "Pest / Disease / Weed",
      "Policy / Planning / Systems / Institutions",
      "Procurement / Machinery / Equipment / Infrastructure",
      "Seeds / Fertilisers / Agro-Chemicals / Pesticides",
      "Semi-arid & arid agriculture",
      "Sub-tropical & tropical agriculture",
      "Testing / Quality Control",
      "Veterinary",
      "Water / Drainage / Irrigation / Flood / Well / Hydrology / Water Sanitation",
      "Zoology / Livestock / Animals / Breeding / Genetics / Cattle / Entomology",
    ],
  },
  {
    category: "Comm. & P.Info",
    subCategories: [
      "Advertising / Information Campaign / Awareness-raising Campaign",
      "Communications",
      "Conferences / Events / Seminars",
      "Information Management / Knowledge Sharing",
      "Journalism",
      "Marketing",
      "Multi-Media",
      "Printing / Publishing",
      "Public Affairs / Public Relations",
      "Media / Radio / Television / Newspapers / Film / Photography",
      "Strategy & Policy",
      "Translation / Interpretation",
      "Writing & Editing / Press Release / Speech",
    ],
  },
  {
    category: "Const. & Engineering",
    subCategories: [
      "Building / Construction / Civil Works / Demolition",
      "Buildings / Offices / Houses",
      "Dredging & Reclamation",
      "Equipment / Material / Procurement / Contracting",
      "Finance / Bonds / Insurance / Cost",
      "Highways / Roads / Bridges / Tunnels",
      "Hydraulic Engineering (dams, pipelines, etc)",
      "Landscape Engineering",
      "Legislation / Permits / Standards",
      "Planning / Architecture / Engineering",
      "Rehabilitation and maintenance works",
      "Site Selection & Land Use",
      "Testing / Assessment / Metering / Protection / Signalling",
      "Works supervision",
    ],
  },
  {
    category: "Consumer Protection",
    subCategories: [
      "Comparative testing",
      "Consumer associations / groups",
      "Consumer protection / Consumer policy / Market surveillance",
      "Consumer redress",
      "Consumer representation",
      "Contracts / Contract terms",
      "Cosmetics / Household appliances / Cars / Dangerous substances/ Hazardous substances / Toys",
      "Information / Labelling",
      "Marketing practices / Sales methods",
      "Product quality control",
      "Product Safety / Food Safety / SPS (Sanitary / Phytosanitary)",
      "Standardisation / Certification / Accreditation / Conformity assessment / Metrology / Laboratory",
      "Sustainable consumption",
      "Warnings",
      "Warranty",
    ],
  },
  {
    category: "Economic Dev",
    subCategories: [
      "Business Centres / Incubators / Business Development / Business Plans / Clustering",
      "Co-operatives",
      "Corporate Governance",
      "Econometrics / Statistics / Income Distribution",
      "Economic Systems / Planning",
      "Employment / Labour",
      "Handicraft",
      "Household / Income Generation",
      "Macroeconomics / Crisis",
      "Matching Grants",
      "Mergers & Acquisitions / Partnerships / Joint Ventures",
      "Micro-Credit",
      "Microeconomics",
      "Privatisation / Public-Private Partnership",
      "Re-engineering (company) / Liquidation",
      "Restructuring (sector / industry)",
      "Small & Medium-Sized Enterprises (SMEs) / Start-ups",
      "Tourism / Hotels / Restaurants / Catering",
    ],
  },
  {
    category: "Education",
    subCategories: [
      "Adult Education / Non-Formal / Literacy",
      "Continuing",
      "Curriculum",
      "Distance Education / e-Learning / Education Technology / Exchange / Scholarship",
      "Facilities / Architecture / Physical Planning / Location",
      "Finance / Accounting / Audit",
      "Higher / University",
      "Library / Documentation Centre",
      "Manpower / Personnel",
      "Marginalised groups / Handicapped / Girls & Women / School attendance",
      "Performance / Examinations / Testing / Measurement / Inspectorate / Supervision / National Qualification framework (NQF)",
      "Policy / Planning / Systems / Institutions / Evaluation / Decentralisation",
      "Pre-School / Early Childhood",
      "Primary",
      "Procurement / Equipment / Materials / Media / Techniques / Textbooks / Publishing / Radio & Television",
      "Research & Development",
      "Secondary",
      "Teachers Training",
      "Technical / Industrial / Vocational",
      "Tertiary",
    ],
  },
  {
    category: "Energy",
    subCategories: [
      "Conservation / Saving / Recovery / Renewable",
      "Drilling / Production / Distribution / Reserves",
      "Electric",
      "Financials / Pricing / Tariffs",
      "Geothermal / Solar / Bio-Mass / Wind / Sea",
      "Heating / Co-Generation",
      "Hydroelectric",
      "Mining / Coal / Lignite / Anthracite",
      "Nuclear",
      "Oil / Gas / Petrol",
      "Planning / Policy",
      "Procurement / Equipment",
    ],
  },
  {
    category: "Environment",
    subCategories: [
      "Bio-diversity / Eco Systems",
      "Botany",
      "Climate / Cyclone",
      "Coastal Zone Management / Marine Biology",
      "Drought & Desertification",
      "Environmental Engineering / Science & Technology",
      "Historic & Cultural Heritage",
      "Natural disasters / Prevention",
      "Natural resources / Earth & Space sciences / Ecology",
      "Policy & Strategy (incl. Sustainability)",
      "Pollution (Air / Water / Soil / Noise / Industrial / Oil)",
      "Procurement",
      "Protected Areas / Parks / Reserves",
      "Protection / Bio-economy / Green economy",
      "Remote Sensing / Early Warning Systems / Surveillance",
      "Standards",
      "Surveys / Impact Assessment",
      "Topography / Geology / Earth Observation",
      "Urban Environment",
      "Waste / Toxic / Hazardous / Solid / Clean Technologies / Processing",
      "Wildlife",
    ],
  },
  {
    category: "Finance & Banking",
    subCategories: [
      "Audit / Accountancy / Due Diligence / Inventory",
      "Balance of Payments",
      "Banking system",
      "Budgets / Public Finance",
      "Capital / Reserves / Liquidity / Cash Flow / Liability / Creditors / Treasury",
      "Co-financing",
      "Corporate finance",
      "Credit / Letters of Credit / Loans / Credit Guarantees",
      "Currency / Exchange",
      "Debt / Indebtedness",
      "Financial Institutions",
      "Insurance",
      "Investment / Venture capital / Portfolio / Securities / Bonds / Stocks / Equities / Funds",
      "Leasing",
      "Market Instruments / Derivatives / Financial Markets / Exchanges",
      "Monetary / Fiscal Policy",
      "Money laundering / Fraud",
      "Payments / Mobile Banking / E-Banking",
      "Pensions",
      "Policy / Planning / Systems",
      "Regulations / Crisis",
      "Reporting / Finance Management",
      "Risk / Sensitivity / Market analysis / Forecasting / Models / Projection",
      "Structural Adjustment",
      "Taxation / Collection",
    ],
  },
  {
    category: "Health",
    subCategories: [
      "Bio-Medicine",
      "Diseases / Vaccination / Epidemic / Prevention / Risks",
      "Economics & Finances / Health Insurance",
      "Genetics",
      "Health Care Buildings / Hospital",
      "HIV / AIDS / STD",
      "Manpower",
      "Maternal-Child health / Maternity / Family planning / Reproductive health / Nursing",
      "Mental Health / Disabled",
      "Nutrition",
      "Occupational Health",
      "Patients' rights / Protection",
      "Pharmaceuticals / Drugs",
      "Policy / Planning / Systems / Organisation / Administration / Management / Systems / e-Health",
      "Primary Health Care",
      "Private Health Care Systems / Infrastructure",
      "Procurement / Logistics / Equipment / Supplies / Distribution / Delivery",
      "Public Health Care Systems / Infrastructure / Districts",
      "Research",
      "Safety / Liability",
      "Sanitation",
    ],
  },
  {
    category: "Humanitarian Aid",
    subCategories: [
      "Food Aid",
      "Land Mines / Mine Clearance",
      "Logistics / Procurement / Equipment",
      "Medical Aid",
      "Policy / Planning",
      "Prevention / Preparedness",
      "Refugees / Returnees / Displaced",
      "Temporary Shelters",
    ],
  },
  {
    category: "It",
    subCategories: [
      "Artificial intelligence",
      "Automation",
      "Computer Networks / Operations / Maintenance and Support / Security",
      "Computer-Assisted Design (CAD/CAM)",
      "Databases / Warehouses / Data Recovery",
      "Decision Support Systems",
      "Geographical Information / Localisation / Surveillance Systems",
      "Hardware / Equipment / Software",
      "Information society / Policy",
      "Internet / Web-based Platforms / e-Commerce / e-Governance",
      "Management Information Systems (MIS)",
      "Teletext",
      "Web Design",
    ],
  },
  {
    category: "Law",
    subCategories: [
      "Administrative Law",
      "Anti-corruption",
      "Bankruptcy / Creditors Rights / Insolvency",
      "Civil law / Public law / Election law / Political Party Law",
      "Commercial / Trade / Contract / Corporate / Industrial / Economic / Competition Law",
      "Computer / e-Commerce / Internet",
      "Constitutional Law",
      "Courts / Tribunals / Law Enforcement / Justice",
      "Criminal Law",
      "Environmental / Energy Law",
      "Financial / Banking / Investment Law",
      "Governmental Law",
      "Human Rights Protection Law",
      "Immigration Law",
      "Insurance Law",
      "International Law",
      "Judges",
      "Labour Law",
      "Law / Legislation / Legal Framework / Regulation / RIA / Reform",
      "Law Harmonisation / Approximation / Pre-accession / Acquis communautaire / European Law",
      "Patent / Trademark / Copyright / Intellectual Property",
      "Property / Estates / Trusts",
      "Secured Transactions / Privacy / Data protection",
      "Securities",
      "State Enterprises Law",
      "Taxation / Income / Chartered Surveyors",
      "Torts / Dispute Settlement / Dialogue / Arbitration / Litigation / Mediation",
      "Transport Law",
    ],
  },
  {
    category: "Prog Management",
    subCategories: [
      "Co-ordination / Aid co-ordination",
      "Cost / Benefits Analysis / Project Budgeting",
      "Country Programming / Programme Development",
      "Identification / Needs Analysis / Formulation / Feasibility Study",
      "Management Systems & Techniques",
      "Monitoring & Evaluation & Assessment / (impact) Studies / Project Audit / Survey",
      "Performance Appraisal",
      "Personnel / Human Resources Management",
      "Procurement / Tender evaluation",
      "Project Cycle Management / Project implementation",
      "Secretarial & Administrative Support",
      "Total Quality Management (TQM) / Quality Control",
      "Training",
    ],
  },
  {
    category: "Public Administration",
    subCategories: [
      "Administrative Agencies",
      "Budget / Budget Support / Public Investment / Finances / Debt",
      "Customs / Excise",
      "Elections / Polling / Voters",
      "Fight against drugs",
      "Foreign Affairs / Diplomacy",
      "Governance",
      "Justice and Home Affairs / Asylum / Immigration / Borders / Passport",
      "Manpower / Recruitment / HR / Grading",
      "Parliament / Political Parties",
      "Planning / Policy / Systems",
      "Police / Defence / Interior / Security / Prison / Fire fighting system",
      "Public Procurement",
      "Public utilities",
      "Reform / Institutional strengthening",
      "Regional / Municipal / Local Authorities / Decentralisation",
      "Regional Country Co-operation / European Integration",
      "Regional Funds",
      "State Enterprises",
      "Terrorism / Corruption / Fight against human traffic",
      "Twinning",
    ],
  },
  {
    category: "Science & Research",
    subCategories: [
      "Chemistry",
      "Earth sciences",
      "Human Sciences",
      "Information Sciences",
      "Life and Health Sciences",
      "Other Sciences",
      "Physics",
      "Procurement / Equipment",
    ],
  },
  {
    category: "Social",
    subCategories: [
      "Anthropology / Tribal / Ethnic Groups",
      "Classification / Norms / Standards",
      "Conflict / Post conflict / Conflict prevention / Political crises",
      "Culture / Religion / Sport / Arts",
      "Democracy / Human Rights",
      "Family Planning",
      "Gender / Women / Equal Opportunities / Discrimination / Re-integration",
      "Migration / Settlement / Resettlement / Border Crossing",
      "Pastoral Groups / Nomads",
      "Policy / Planning / Systems / Reform / Poverty Alleviation",
      "Procurement / Equipment / Vehicles / Supplies / Facilities / Rent",
      "Self-help / Grass-roots",
      "Social Security / Pension / Protection",
      "Statistics / Demography / Population / Census / Opinion Polling / Research",
      "Volunteering / NGO / CBO / Trade Unions / Civil Society",
      "Vulnerable Groups / Street Children / Minorities",
      "Youth",
    ],
  },
  {
    category: "Telecommunications",
    subCategories: [
      "Mobile systems / Services / Equipment",
      "Policy / Planning / Teletext",
      "Post / Courier service",
      "Procurement / Equipment / Systems",
      "Tariffs",
    ],
  },
  {
    category: "Trade & Industry",
    subCategories: [
      "Chambers of Commerce",
      "Commodities / Raw Materials",
      "Export / Competition",
      "Foreign Direct Investments / Investment promotion",
      "Free Trade Zones / Industrial Parks / Estates",
      "Import",
      "Industry / Industrial Products",
      "Licencing / Patents / Trademarks",
      "Logistics",
      "Market Analysis / Market Surveillance",
      "Marketing / Direct Marketing",
      "Policy / Planning",
      "Pricing",
      "Procurement / Purchasing & Supply / Sales",
      "Promotion / Aids / Facilitation",
      "Retail Management",
      "Sponsorship",
      "Tariff / Barriers / Contracts / Terms / Restrictions",
      "Trade / Global trade",
    ],
  },
  {
    category: "Transport",
    subCategories: [
      "Air / Aviation / Airport",
      "Freight / Cargo",
      "Inter-modal / Multi-modal",
      "Investment / Finances",
      "Logistics",
      "Navigational Aids",
      "Policy & Planning / Models",
      "Procurement / Equipment / Vehicles / Maintenance",
      "Rail",
      "Regulation & Pricing",
      "Road / Public transportation",
      "Safety",
      "Traffic / Origin-Destination Surveys",
      "Warehouses & Storage",
      "Water Navigation / Ports / Shipping",
    ],
  },
  {
    category: "Humanitarian",
    subCategories: [
      "Food Aid",
      "Land Mines / Mine Clearance",
      "Logistics / Procurement / Equipment",
      "Medical Aid",
      "Policy / Planning",
      "Prevention / Preparedness",
      "Refugees / Returnees / Displaced",
      "Temporary Shelters",
    ],
  },
  {
    category: "Urban Development",
    subCategories: [
      "Community Participation / Employment",
      "Energy",
      "Engineering / Infrastructure / Implementation / Building / Works Supervision",
      "Finance / Budgeting / Investment / Valuation / Taxation",
      "Land Use",
      "Pedestrian",
      "Planning / Models / Policies",
      "Property / Facilities / Asset Management",
      "Public utilities",
      "Self-help Programmes",
      "Services / Facilities / Maintenance / Cleaning services",
      "Shelter / Housing / Habitat",
      "Slums",
      "Standards & Regulations",
      "Survey",
      "Transport",
      "Water / Drainage / Irrigation / Flood / Well / Hydrology",
    ],
  },
];


export const geoData = [
  {
    category: "Central & Eastern Europe",
    subCategories: [
      "Armenia",
      "Azerbaijan",
      "Belarus",
      "Czech Republic",
      "Estonia",
      "Georgia",
      "Hungary",
      "Latvia",
      "Lithuania",
      "Moldova",
      "Poland",
      "Russian Federation",
      "Slovakia",
      "Slovenia",
      "Ukraine",
    ],
  },
  {
    category: "South-East Europe",
    subCategories: [
      "Albania",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Kosovo",
      "Montenegro",
      "North Macedonia",
      "Romania",
      "Serbia",
    ],
  },
  {
    category: "Western Europe",
    subCategories: [
      "Andorra",
      "Austria",
      "Belgium",
      "Denmark",
      "Faroe Islands",
      "Finland",
      "France",
      "Germany",
      "Gibraltar",
      "Greece",
      "Greenland",
      "Iceland",
      "Ireland",
      "Italy",
      "Liechtenstein",
      "Luxembourg",
      "Malta",
      "Monaco",
      "Netherlands",
      "Norway",
      "Portugal",
      "San Marino",
      "Spain",
      "Svalbard and Jan Mayen Islands",
      "Sweden",
      "Switzerland",
      "United Kingdom",
      "Vatican City",
    ],
  },

  {
    category: "Central Africa",
    subCategories: [
      "Burundi",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Congo (Brazaville)",
      "Congo, Democratic Republic of the",
      "Equatorial Guinea",
      "Gabon",
      "Rwanda",
      "The Sahel",
    ],
  },
  {
    category: "Eastern Africa",
    subCategories: [
      "Comoros",
      "Djibouti",
      "Eritrea",
      "Ethiopia",
      "Heard and McDonald Islands",
      "Kenya",
      "Madagascar",
      "Mayotte",
      "Reunion (France)",
      "Seychelles",
      "Somalia",
      "South Sudan",
      "Sudan",
      "Tanzania",
      "Uganda",
    ],
  },
  {
    category: "Northern Africa",
    subCategories: [
      "Algeria",
      "Egypt",
      "Libya",
      "Mauritania",
      "Morocco",
      "Tunisia",
      "Western Sahara",
    ],
  },
  {
    category: "Southern Africa",
    subCategories: [
      "Angola",
      "Botswana",
      "Lesotho",
      "Malawi",
      "Mauritius",
      "Mozambique",
      "Namibia",
      "Saint Helena",
      "South Africa",
      "Swaziland / Kingdom of Eswatini",
      "Zambia",
    ],
  },
  {
    category: "Western Africa",
    subCategories: [
      "Benin",
      "Burkina Faso",
      "Cape Verde",
      "Gambia, The",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Ivory Coast",
      "Liberia",
      "Mali",
      "Niger",
      "Nigeria",
      "Sao Tome and Principe",
      "Senegal",
      "Sierra Leone",
      "Togo",
    ],
  },
  {
    category: "Central Asia",
    subCategories: [
      "Kazakhstan",
      "Kyrgyz Republic",
      "Tajikistan",
      "Turkmenistan",
      "Uzbekistan",
    ],
  },
  {
    category: "Middle East",
    subCategories: [
      "Bahrain",
      "Iran Islamic Republic",
      "Iraq",
      "Israel",
      "Jordan",
      "Kuwait",
      "Lebanon",
      "Oman",
      "Palestine / West Bank and Gaza",
      "Qatar",
      "Saudi Arabia",
      "Syria",
      "Turkey",
      "United Arab Emirates",
      "Yemen",
    ],
  },
  {
    category: "North-East Asia",
    subCategories: [
      "China",
      "Hong Kong (China)",
      "Japan",
      "Korea, North",
      "Korea, South",
      "Macau (China)",
      "Mongolia",
    ],
  },
  {
    category: "South-East Asia",
    subCategories: [
      "Brunei Darussalam",
      "Cambodia",
      "East Timor",
      "Indonesia",
      "Laos",
      "Malaysia",
      "Myanmar",
      "Philippines",
      "Singapore",
      "Taiwan",
      "Thailand",
      "Vietnam",
    ],
  },
  {
    category: "Southern Asia",
    subCategories: [
      "Afghanistan",
      "Bangladesh",
      "Bhutan",
      "British Indian Ocean Territory",
      "India",
      "Maldives",
      "Nepal",
      "Pakistan",
      "Sri Lanka",
    ],
  },
  {
    category: "Oceania",
    subCategories: [
      "American Samoa",
      "Australia",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Cook Islands",
      "Fiji",
      "French Polynesia",
      "Kiribati",
      "Marshall Islands",
      "Micronesia, Federated States of",
      "Nauru",
      "New Caledonia",
      "New Zealand",
      "Niue",
      "Norfolk Island",
      "Northern Mariana Islands",
      "Palau",
      "Papua New Guinea",
      "Samoa",
      "Solomon Islands",
      "Tokelau",
      "Tonga",
      "Tuvalu",
      "Vanuatu",
      "Wallis and Futuna",
    ],
  },
  {
    category: "Central America",
    subCategories: [
      "Anguilla",
      "Antigua and Barbuda",
      "Aruba",
      "Bahamas",
      "Barbados",
      "Belize",
      "Bermuda",
      "Cayman Islands",
      "Costa Rica",
      "Cuba",
      "Dominica",
      "Dominican Republic",
      "El Salvador",
      "Grenada",
      "Guadeloupe (France)",
      "Guatemala",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Martinique (France)",
      "Mexico",
      "Montserrat",
      "Netherlands Antilles",
      "Nicaragua",
      "Panama",
      "Puerto Rico",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Trinidad and Tobago",
      "Turks and Caicos Islands",
      "Virgin Islands (British)",
      "Virgin Islands (USA)",
    ],
  },
  {
    category: "North America",
    subCategories: [
      "Canada",
      "Saint Pierre and Miquelon",
      "United States of America",
    ],
  },
  {
    category: " South America",
    subCategories: [
      "Brunei Darussalam",
      "Cambodia",
      "East Timor",
      "Indonesia",
      "Laos",
    ],
  },
  {
    category: "South",
    subCategories: [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Falkland Islands",
      "French Guiana",
      "Guyana",
      "Paraguay",
      "Peru",
      "Pitcairn Island",
      "South Georgia and the South Sandwich Islands",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
  },
];

export const fundingAgenciesData = [
  "ADB – Asian Development Bank",
  "AfDB – African Development Bank",
  "EIB – European Investment Bank",
  "GCF – Green Climate Fund",
  "GF – The Global Fund to Fight AIDS, Tuberculosis and Malaria",
  "GIZ – Deutsche Gesellschaft für Internationale Zusammenarbeit",
  "Global Affairs Canada (AMC)",
  "JICA – Japan International Cooperation Agency",
  "KOICA – Korea International Cooperation Agency",
  "NORAD – Norwegian Agency for Development Cooperation",
  "SIDA – Swedish International Development Cooperation Agency",
  "UNDP – United Nations Development Programme",
  "UNFPA – United Nations Population Fund",
  "UNHCR – United Nations High Commissioner for Refugees",
  "UNICEF – United Nations Children’s Fund",
  "UNWFP – United Nations World Food Programme",
  "USAID – U.S. Agency for International Development",
  "WB – World Bank",
  "WHO – World Health Organization",
];

/* ── Expertise sub-categories ──
   The option list behind "Areas of expertise". Extracted from
   QuickUploadPage / BuildCvPage, which each held an identical copy. */
export const subCategory = [
  { value: "Agro-industry" },
  { value: "Food" },
  { value: "Nutrition" },
  { value: "Biotechnology" },
  { value: "Credit" },
  { value: "Insurance" },
  { value: "Clearing" },
  { value: "Economics" },
  { value: "Finance" },
  { value: "Cultivation" },
  { value: "Harvesting" },
  { value: "Crop" },
  { value: "Drying" },
  { value: "Processing" },
  { value: "Scarifying" },
  { value: "Pelletizing" },
  { value: "Early Warning Systems" },
  { value: "Surveillance (Crops)" },
  { value: "Farm" },
  { value: "Co-operatives" },
  { value: "Associations" },
  { value: "Community Centres" },
  { value: "Community Participation" },
  { value: "Fisheries" },
  { value: "Aquaculture" },
  { value: "Forestry" },
  { value: "Fruits & Vegetables" },
  { value: "Horticulture" },
  { value: "Land" },
  { value: "Erosion" },
  { value: "Soil" },
  { value: "Conservation" },
  { value: "Mapping" },
  { value: "Cadastre" },
  { value: "Meat" },
  { value: "Dairy" },
  { value: "Mechanisation" },
  { value: "Production" },
  { value: "Packaging" },
  { value: "Storage" },
  { value: "Distribution" },
  { value: "Marketing" },
  { value: "Pest" },
  { value: "Disease" },
  { value: "Weed" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Systems" },
  { value: "Institutions" },
  { value: "Procurement" },
  { value: "Machinery" },
  { value: "Equipment" },
  { value: "Infrastructure" },
  { value: "Seeds" },
  { value: "Fertilisers" },
  { value: "Agro-Chemicals" },
  { value: "Pesticides" },
  { value: "Semi-arid agriculture" },
  { value: "arid agriculture" },
  { value: "Sub-tropical agriculture" },
  { value: "tropical agriculture" },
  { value: "Testing" },
  { value: "Quality Control" },
  { value: "Veterinary" },
  { value: "Water" },
  { value: "Drainage" },
  { value: "Irrigation" },
  { value: "Flood" },
  { value: "Well" },
  { value: "Hydrology" },
  { value: "Water Sanitation" },
  { value: "Zoology" },
  { value: "Livestock" },
  { value: "Animals" },
  { value: "Breeding" },
  { value: "Genetics" },
  { value: "Cattle" },
  { value: "Entomology" },
  { value: "Advertising" },
  { value: "Information Campaign" },
  { value: "Awareness-raising Campaign" },
  { value: "Communications" },
  { value: "Conferences" },
  { value: "Events" },
  { value: "Seminars" },
  { value: "Information Management" },
  { value: "Knowledge Sharing" },
  { value: "Journalism" },
  { value: "Multi-Media" },
  { value: "Printing" },
  { value: "Publishing" },
  { value: "Public Affairs" },
  { value: "Public Relations" },
  { value: "Media" },
  { value: "Radio" },
  { value: "Television" },
  { value: "Newspapers" },
  { value: "Film" },
  { value: "Photography" },
  { value: "Strategy & Policy" },
  { value: "Translation" },
  { value: "Interpretation" },
  { value: "Writing & Editing" },
  { value: "Press Release" },
  { value: "Speech" },
  { value: "Building" },
  { value: "Construction" },
  { value: "Civil Works" },
  { value: "Demolition" },
  { value: "Buildings" },
  { value: "Offices" },
  { value: "Houses" },
  { value: "Dredging & Reclamation" },
  { value: "Material" },
  { value: "Contracting" },
  { value: "Bonds" },
  { value: "Cost" },
  { value: "Highways" },
  { value: "Roads" },
  { value: "Bridges" },
  { value: "Tunnels" },
  { value: "Hydraulic Engineering (dams, pipelines, etc)" },
  { value: "Landscape Engineering" },
  { value: "Legislation" },
  { value: "Permits" },
  { value: "Standards" },
  { value: "Architecture" },
  { value: "Engineering" },
  { value: "Rehabilitation and maintenance works" },
  { value: "Site Selection" },
  { value: "Land Use" },
  { value: "Assessment" },
  { value: "Metering" },
  { value: "Protection" },
  { value: "Signalling" },
  { value: "Works supervision" },
  { value: "Comparative testing" },
  { value: "Consumer associations" },
  { value: "groups" },
  { value: "Consumer protection" },
  { value: "Consumer policy" },
  { value: "Market surveillance" },
  { value: "Consumer redress" },
  { value: "Consumer representation" },
  { value: "Contracts" },
  { value: "Contract terms" },
  { value: "Cosmetics" },
  { value: "Household appliances" },
  { value: "Cars" },
  { value: "Dangerous substances" },
  { value: "Hazardous substances" },
  { value: "Toys" },
  { value: "Information" },
  { value: "Labelling" },
  { value: "Marketing practices" },
  { value: "Sales methods" },
  { value: "Product quality control" },
  { value: "Product Safety" },
  { value: "Food Safety" },
  { value: "SPS (Sanitary / Phytosanitary)" },
  { value: "Standardisation" },
  { value: "Certification" },
  { value: "Accreditation" },
  { value: "Conformity assessment" },
  { value: "Metrology" },
  { value: "Laboratory" },
  { value: "Sustainable consumption" },
  { value: "Warnings" },
  { value: "Warranty" },
  { value: "Business Centres" },
  { value: "Incubators" },
  { value: "Business Development" },
  { value: "Business Plans" },
  { value: "Clustering" },
  { value: "Co-operatives" },
  { value: "Corporate Governance" },
  { value: "Econometrics" },
  { value: "Statistics" },
  { value: "Income Distribution" },
  { value: "Economic Systems" },
  { value: "Planning" },
  { value: "Employment" },
  { value: "Labour" },
  { value: "Handicraft" },
  { value: "Household" },
  { value: "Income Generation" },
  { value: "Macroeconomics" },
  { value: "Crisis" },
  { value: "Matching Grants" },
  { value: "Mergers & Acquisitions" },
  { value: "Partnerships" },
  { value: "Joint Ventures" },
  { value: "Micro-Credit" },
  { value: "Microeconomics" },
  { value: "Privatisation" },
  { value: "Public-Private Partnership" },
  { value: "Re-engineering (company)" },
  { value: "Liquidation" },
  { value: "Restructuring (sector" },
  { value: "industry)" },
  { value: "Small & Medium-Sized Enterprises (SMEs)" },
  { value: "Start-ups" },
  { value: "Tourism" },
  { value: "Hotels" },
  { value: "Restaurants" },
  { value: "Catering" },
  { value: "Adult Education" },
  { value: "Non-Formal" },
  { value: "Literacy" },
  { value: "Continuing" },
  { value: "Curriculum" },
  { value: "Distance Education" },
  { value: "e-Learning" },
  { value: "Education Technology" },
  { value: "Exchange" },
  { value: "Scholarship" },
  { value: "Facilities" },
  { value: "Architecture" },
  { value: "Physical Planning" },
  { value: "Location" },
  { value: "Finance" },
  { value: "Accounting" },
  { value: "Audit" },
  { value: "Higher" },
  { value: "University" },
  { value: "Library" },
  { value: "Documentation Centre" },
  { value: "Manpower" },
  { value: "Personnel" },
  { value: "Marginalised groups" },
  { value: "Handicapped" },
  { value: "Girls & Women" },
  { value: "School attendance" },
  { value: "Performance" },
  { value: "Examinations" },
  { value: "Testing" },
  { value: "Measurement" },
  { value: "Inspectorate" },
  { value: "Supervision" },
  { value: "National Qualification framework (NQF)" },
  { value: "Policy" },
  { value: "Systems" },
  { value: "Institutions" },
  { value: "Evaluation" },
  { value: "Decentralisation" },
  { value: "Pre-School" },
  { value: "Early Childhood" },
  { value: "Primary" },
  { value: "Procurement" },
  { value: "Equipment" },
  { value: "Materials" },
  { value: "Media" },
  { value: "Techniques" },
  { value: "Textbooks" },
  { value: "Publishing" },
  { value: "Radio & Television" },
  { value: "Research & Development" },
  { value: "Secondary" },
  { value: "Teachers Training" },
  { value: "Technical" },
  { value: "Industrial" },
  { value: "Vocational" },
  { value: "Tertiary" },
  { value: "Conservation" },
  { value: "Saving" },
  { value: "Recovery" },
  { value: "Renewable" },
  { value: "Drilling" },
  { value: "Production" },
  { value: "Distribution" },
  { value: "Reserves" },
  { value: "Electric" },
  { value: "Financials" },
  { value: "Pricing" },
  { value: "Tariffs" },
  { value: "Geothermal" },
  { value: "Solar" },
  { value: "Bio-Mass" },
  { value: "Wind" },
  { value: "Sea" },
  { value: "Heating" },
  { value: "Co-Generation" },
  { value: "Hydroelectric" },
  { value: "Mining" },
  { value: "Coal" },
  { value: "Lignite" },
  { value: "Anthracite" },
  { value: "Nuclear" },
  { value: "Oil" },
  { value: "Gas" },
  { value: "Petrol" },
  { value: "Planning" },
  { value: "Policy" },
  { value: "Procurement" },
  { value: "Equipment" },
  { value: "Bio-diversity" },
  { value: "Eco Systems" },
  { value: "Botany" },
  { value: "Climate" },
  { value: "Cyclone" },
  { value: "Coastal Zone Management" },
  { value: "Marine Biology" },
  { value: "Drought & Desertification" },
  { value: "Environmental Engineering" },
  { value: "Science & Technology" },
  { value: "Historic & Cultural Heritage" },
  { value: "Natural disasters" },
  { value: "Prevention" },
  { value: "Natural resources" },
  { value: "Earth & Space sciences" },
  { value: "Ecology" },
  { value: "Policy & Strategy (incl. Sustainability)" },
  { value: "Pollution (Air)" },
  { value: "Pollution (Water)" },
  { value: "Pollution (Soil)" },
  { value: "Pollution (Noise)" },
  { value: "Pollution (Industrial)" },
  { value: "Pollution (Oil)" },
  { value: "Protected Areas" },
  { value: "Parks" },
  { value: "Reserves" },
  { value: "Protection" },
  { value: "Bio-economy" },
  { value: "Green economy" },
  { value: "Remote Sensing" },
  { value: "Early Warning Systems" },
  { value: "Surveillance" },
  { value: "Standards" },
  { value: "Surveys" },
  { value: "Impact Assessment" },
  { value: "Topography" },
  { value: "Geology" },
  { value: "Earth Observation" },
  { value: "Urban Environment" },
  { value: "Waste" },
  { value: "Toxic" },
  { value: "Hazardous" },
  { value: "Solid" },
  { value: "Clean Technologies" },
  { value: "Processing" },
  { value: "Wildlife" },
  { value: "Audit" },
  { value: "Accountancy" },
  { value: "Due Diligence" },
  { value: "Inventory" },
  { value: "Balance of Payments" },
  { value: "Banking system" },
  { value: "Budgets" },
  { value: "Public Finance" },
  { value: "Capital" },
  { value: "Reserves" },
  { value: "Liquidity" },
  { value: "Cash Flow" },
  { value: "Liability" },
  { value: "Creditors" },
  { value: "Treasury" },
  { value: "Co-financing" },
  { value: "Corporate finance" },
  { value: "Credit" },
  { value: "Letters of Credit" },
  { value: "Loans" },
  { value: "Credit Guarantees" },
  { value: "Currency" },
  { value: "Exchange" },
  { value: "Debt" },
  { value: "Indebtedness" },
  { value: "Financial Institutions" },
  { value: "Insurance" },
  { value: "Investment" },
  { value: "Venture capital" },
  { value: "Portfolio" },
  { value: "Securities" },
  { value: "Bonds" },
  { value: "Stocks" },
  { value: "Equities" },
  { value: "Funds" },
  { value: "Leasing" },
  { value: "Market Instruments" },
  { value: "Derivatives" },
  { value: "Financial Markets" },
  { value: "Exchanges" },
  { value: "Monetary" },
  { value: "Fiscal Policy" },
  { value: "Money laundering" },
  { value: "Fraud" },
  { value: "Payments" },
  { value: "Mobile Banking" },
  { value: "E-Banking" },
  { value: "Pensions" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Systems" },
  { value: "Regulations" },
  { value: "Crisis" },
  { value: "Reporting" },
  { value: "Finance Management" },
  { value: "Risk" },
  { value: "Sensitivity" },
  { value: "Market analysis" },
  { value: "Forecasting" },
  { value: "Models" },
  { value: "Projection" },
  { value: "Structural Adjustment" },
  { value: "Taxation" },
  { value: "Collection" },
  { value: "Bio-Medicine" },
  { value: "Diseases" },
  { value: "Vaccination" },
  { value: "Epidemic" },
  { value: "Prevention" },
  { value: "Risks" },
  { value: "Economics & Finances" },
  { value: "Health Insurance" },
  { value: "Genetics" },
  { value: "Health Care Buildings" },
  { value: "Hospital" },
  { value: "HIV" },
  { value: "AIDS" },
  { value: "STD" },
  { value: "Manpower" },
  { value: "Maternal-Child health" },
  { value: "Maternity" },
  { value: "Family planning" },
  { value: "Reproductive health" },
  { value: "Nursing" },
  { value: "Mental Health" },
  { value: "Disabled" },
  { value: "Nutrition" },
  { value: "Occupational Health" },
  { value: "Patients' rights" },
  { value: "Protection" },
  { value: "Pharmaceuticals" },
  { value: "Drugs" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Systems" },
  { value: "Organisation" },
  { value: "Administration" },
  { value: "Management" },
  { value: "e-Health" },
  { value: "Primary Health Care" },
  { value: "Private Health Care Systems" },
  { value: "Infrastructure" },
  { value: "Procurement" },
  { value: "Logistics" },
  { value: "Equipment" },
  { value: "Supplies" },
  { value: "Distribution" },
  { value: "Delivery" },
  { value: "Public Health Care Systems" },
  { value: "Districts" },
  { value: "Research" },
  { value: "Safety" },
  { value: "Liability" },
  { value: "Sanitation" },
  { value: "Food Aid" },
  { value: "Land Mines" },
  { value: "Mine Clearance" },
  { value: "Medical Aid" },
  { value: "Prevention" },
  { value: "Preparedness" },
  { value: "Refugees" },
  { value: "Returnees" },
  { value: "Displaced" },
  { value: "Temporary Shelters" },
  { value: "Artificial intelligence" },
  { value: "Automation" },
  { value: "Computer Networks" },
  { value: "Operations" },
  { value: "Maintenance and Support" },
  { value: "Security" },
  { value: "Computer-Assisted Design (CAD/CAM)" },
  { value: "Databases" },
  { value: "Warehouses" },
  { value: "Data Recovery" },
  { value: "Decision Support Systems" },
  { value: "Geographical Information" },
  { value: "Localisation" },
  { value: "Surveillance Systems" },
  { value: "Hardware" },
  { value: "Software" },
  { value: "Information society" },
  { value: "Internet" },
  { value: "Web-based Platforms" },
  { value: "e-Commerce" },
  { value: "e-Governance" },
  { value: "Management Information Systems (MIS)" },
  { value: "Teletext" },
  { value: "Web Design" },
  { value: "Administrative Law" },
  { value: "Anti-corruption" },
  { value: "Bankruptcy" },
  { value: "Creditors Rights" },
  { value: "Insolvency" },
  { value: "Civil law" },
  { value: "Public law" },
  { value: "Election law" },
  { value: "Political Party Law" },
  { value: "Commercial Law" },
  { value: "Trade Law" },
  { value: "Contract Law" },
  { value: "Corporate Law" },
  { value: "Industrial Law" },
  { value: "Economic Law" },
  { value: "Competition Law" },
  { value: "Computer Law" },
  { value: "e-Commerce Law" },
  { value: "Internet Law" },
  { value: "Constitutional Law" },
  { value: "Courts" },
  { value: "Tribunals" },
  { value: "Law Enforcement" },
  { value: "Justice" },
  { value: "Criminal Law" },
  { value: "Environmental Law" },
  { value: "Energy Law" },
  { value: "Financial Law" },
  { value: "Banking Law" },
  { value: "Investment Law" },
  { value: "Governmental Law" },
  { value: "Human Rights Protection Law" },
  { value: "Immigration Law" },
  { value: "Insurance Law" },
  { value: "International Law" },
  { value: "Judges" },
  { value: "Labour Law" },
  { value: "Law" },
  { value: "Legislation" },
  { value: "Legal Framework" },
  { value: "Regulation" },
  { value: "RIA" },
  { value: "Reform" },
  { value: "Law Harmonisation" },
  { value: "Approximation" },
  { value: "Pre-accession" },
  { value: "Acquis communautaire" },
  { value: "European Law" },
  { value: "Patent" },
  { value: "Trademark" },
  { value: "Copyright" },
  { value: "Intellectual Property" },
  { value: "Property" },
  { value: "Estates" },
  { value: "Trusts" },
  { value: "Secured Transactions" },
  { value: "Privacy" },
  { value: "Data protection" },
  { value: "Securities" },
  { value: "State Enterprises Law" },
  { value: "Taxation" },
  { value: "Income" },
  { value: "Chartered Surveyors" },
  { value: "Torts" },
  { value: "Dispute Settlement" },
  { value: "Dialogue" },
  { value: "Arbitration" },
  { value: "Litigation" },
  { value: "Mediation" },
  { value: "Transport Law" },
  { value: "Co-ordination" },
  { value: "Aid co-ordination" },
  { value: "Cost Analysis" },
  { value: "Benefits Analysis" },
  { value: "Project Budgeting" },
  { value: "Country Programming" },
  { value: "Programme Development" },
  { value: "Identification" },
  { value: "Needs Analysis" },
  { value: "Formulation" },
  { value: "Feasibility Study" },
  { value: "Management Systems & Techniques" },
  { value: "Monitoring" },
  { value: "Evaluation" },
  { value: "Assessment" },
  { value: "(impact) Studies" },
  { value: "Project Audit" },
  { value: "Survey" },
  { value: "Performance Appraisal" },
  { value: "Personnel" },
  { value: "Human Resources Management" },
  { value: "Procurement" },
  { value: "Tender evaluation" },
  { value: "Project Cycle Management" },
  { value: "Project implementation" },
  { value: "Secretarial Support" },
  { value: "Administrative Support" },
  { value: "Total Quality Management (TQM)" },
  { value: "Quality Control" },
  { value: "Training" },
  { value: "Administrative Agencies" },
  { value: "Budget" },
  { value: "Budget Support" },
  { value: "Public Investment" },
  { value: "Finances" },
  { value: "Debt" },
  { value: "Customs" },
  { value: "Excise" },
  { value: "Elections" },
  { value: "Polling" },
  { value: "Voters" },
  { value: "Fight against drugs" },
  { value: "Foreign Affairs" },
  { value: "Diplomacy" },
  { value: "Governance" },
  { value: "Justice and Home Affairs" },
  { value: "Asylum" },
  { value: "Immigration" },
  { value: "Borders" },
  { value: "Passport" },
  { value: "Manpower" },
  { value: "Recruitment" },
  { value: "HR" },
  { value: "Grading" },
  { value: "Parliament" },
  { value: "Political Parties" },
  { value: "Planning" },
  { value: "Policy" },
  { value: "Systems" },
  { value: "Police" },
  { value: "Defence" },
  { value: "Interior" },
  { value: "Security" },
  { value: "Prison" },
  { value: "Fire fighting system" },
  { value: "Public Procurement" },
  { value: "Public utilities" },
  { value: "Institutional strengthening" },
  { value: "Regional Authorities" },
  { value: "Municipal Authorities" },
  { value: "Local Authorities" },
  { value: "Decentralisation" },
  { value: "Regional Country Co-operation" },
  { value: "European Integration" },
  { value: "Regional Funds" },
  { value: "State Enterprises" },
  { value: "Terrorism" },
  { value: "Corruption" },
  { value: "Fight against human traffic" },
  { value: "Twinning" },
  { value: "Chemistry" },
  { value: "Earth sciences" },
  { value: "Human Sciences" },
  { value: "Information Sciences" },
  { value: "Life and Health Sciences" },
  { value: "Other Sciences" },
  { value: "Physics" },
  { value: "Procurement" },
  { value: "Equipment" },
  { value: "Anthropology" },
  { value: "Tribal" },
  { value: "Ethnic Groups" },
  { value: "Classification" },
  { value: "Norms" },
  { value: "Standards" },
  { value: "Conflict" },
  { value: "Post conflict" },
  { value: "Conflict prevention" },
  { value: "Political crises" },
  { value: "Culture" },
  { value: "Religion" },
  { value: "Sport" },
  { value: "Arts" },
  { value: "Democracy" },
  { value: "Human Rights" },
  { value: "Family Planning" },
  { value: "Gender" },
  { value: "Women" },
  { value: "Equal Opportunities" },
  { value: "Discrimination" },
  { value: "Re-integration" },
  { value: "Migration" },
  { value: "Settlement" },
  { value: "Resettlement" },
  { value: "Border Crossing" },
  { value: "Pastoral Groups" },
  { value: "Nomads" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Systems" },
  { value: "Reform" },
  { value: "Poverty Alleviation" },
  { value: "Vehicles" },
  { value: "Supplies" },
  { value: "Facilities" },
  { value: "Rent" },
  { value: "Self-help" },
  { value: "Grass-roots" },
  { value: "Social Security" },
  { value: "Pension" },
  { value: "Protection" },
  { value: "Statistics" },
  { value: "Demography" },
  { value: "Population" },
  { value: "Census" },
  { value: "Opinion Polling" },
  { value: "Research" },
  { value: "Volunteering" },
  { value: "NGO" },
  { value: "CBO" },
  { value: "Trade Unions" },
  { value: "Civil Society" },
  { value: "Vulnerable Groups" },
  { value: "Street Children" },
  { value: "Minorities" },
  { value: "Youth" },
  { value: "Mobile systems" },
  { value: "Services" },
  { value: "Post" },
  { value: "Courier service" },
  { value: "Teletext" },
  { value: "Tariffs" },
  { value: "Chambers of Commerce" },
  { value: "Commodities" },
  { value: "Raw Materials" },
  { value: "Export" },
  { value: "Competition" },
  { value: "Foreign Direct Investments" },
  { value: "Investment promotion" },
  { value: "Free Trade Zones" },
  { value: "Industrial Parks" },
  { value: "Estates" },
  { value: "Import" },
  { value: "Industry" },
  { value: "Industrial Products" },
  { value: "Licencing" },
  { value: "Patents" },
  { value: "Trademarks" },
  { value: "Logistics" },
  { value: "Market Analysis" },
  { value: "Market Surveillance" },
  { value: "Marketing" },
  { value: "Direct Marketing" },
  { value: "Policy" },
  { value: "Planning" },
  { value: "Pricing" },
  { value: "Procurement" },
  { value: "Purchasing & Supply" },
  { value: "Sales" },
  { value: "Promotion" },
  { value: "Aids" },
  { value: "Facilitation" },
  { value: "Retail Management" },
  { value: "Sponsorship" },
  { value: "Tariff" },
  { value: "Barriers" },
  { value: "Contracts" },
  { value: "Terms" },
  { value: "Restrictions" },
  { value: "Trade" },
  { value: "Global trade" },
  { value: "Air" },
  { value: "Aviation" },
  { value: "Airport" },
  { value: "Freight" },
  { value: "Cargo" },
  { value: "Inter-modal" },
  { value: "Multi-modal" },
  { value: "Investment" },
  { value: "Finances" },
  { value: "Navigational Aids" },
  { value: "Models" },
  { value: "Equipment" },
  { value: "Vehicles" },
  { value: "Maintenance" },
  { value: "Rail" },
  { value: "Regulation" },
  { value: "Road" },
  { value: "Public transportation" },
  { value: "Safety" },
  { value: "Traffic" },
  { value: "Origin-Destination Surveys" },
  { value: "Warehouses" },
  { value: "Storage" },
  { value: "Water Navigation" },
  { value: "Ports" },
  { value: "Shipping" },
  { value: "Food Aid" },
  { value: "Land Mines" },
  { value: "Mine Clearance" },
  { value: "Medical Aid" },
  { value: "Prevention" },
  { value: "Preparedness" },
  { value: "Refugees" },
  { value: "Returnees" },
  { value: "Displaced" },
  { value: "Temporary Shelters" },
  { value: "Community Participation" },
  { value: "Employment" },
  { value: "Energy" },
  { value: "Engineering" },
  { value: "Infrastructure" },
  { value: "Implementation" },
  { value: "Building" },
  { value: "Works Supervision" },
  { value: "Finance" },
  { value: "Budgeting" },
  { value: "Investment" },
  { value: "Valuation" },
  { value: "Taxation" },
  { value: "Land Use" },
  { value: "Pedestrian" },
  { value: "Planning" },
  { value: "Models" },
  { value: "Policies" },
  { value: "Property" },
  { value: "Facilities" },
  { value: "Asset Management" },
  { value: "Public utilities" },
  { value: "Self-help Programmes" },
  { value: "Services" },
  { value: "Maintenance" },
  { value: "Cleaning services" },
  { value: "Shelter" },
  { value: "Housing" },
  { value: "Habitat" },
  { value: "Slums" },
  { value: "Standards & Regulations" },
  { value: "Survey" },
  { value: "Transport" },
  { value: "Water" },
  { value: "Drainage" },
  { value: "Irrigation" },
  { value: "Flood" },
  { value: "Well" },
  { value: "Hydrology" },
];

/* Deduped (case-insensitive) and alphabetised — ready for a Select. */
export const expertiseOptions = subCategory
  .filter(
    (item, index, self) =>
      index ===
      self.findIndex((t) => t.value.toLowerCase() === item.value.toLowerCase())
  )
  .sort((a, b) => a.value.toLowerCase().localeCompare(b.value.toLowerCase()))
  .map(({ value }) => ({ value, label: value }));

/* ── Countries ──
   Built from the country-list package so the option set stays current.
   Names are capitalised to match how they are stored on Expert.country. */
export const countryOptions = Object.entries(getNameList())
  .map(([name]) => {
    // Split on spaces rather than using \b, which mis-capitalises names
    // starting with a non-ASCII letter (e.g. "Åland Islands").
    const label = name
      .split(" ")
      .map((word) => (word ? word[0].toLocaleUpperCase() + word.slice(1) : word))
      .join(" ");
    return { value: label, label };
  })
  .sort((a, b) => a.label.localeCompare(b.label));

/* ── Nationalities ──
   Extracted from QuickUploadPage / BuildCvPage / EditExpertPage, which
   each held an identical copy. */
export const nationalityOptions = [
  { value: "Afghan", label: "Afghan" },
  { value: "Albanian", label: "Albanian" },
  { value: "Algerian", label: "Algerian" },
  { value: "American", label: "American" },
  { value: "Andorran", label: "Andorran" },
  { value: "Angolan", label: "Angolan" },
  { value: "Antiguan", label: "Antiguan" },
  { value: "Argentine", label: "Argentine" },
  { value: "Armenian", label: "Armenian" },
  { value: "Australian", label: "Australian" },
  { value: "Austrian", label: "Austrian" },
  { value: "Azerbaijani", label: "Azerbaijani" },
  { value: "Bahamian", label: "Bahamian" },
  { value: "Bahraini", label: "Bahraini" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Barbadian", label: "Barbadian" },
  { value: "Basotho", label: "Basotho" },
  { value: "Belarusian", label: "Belarusian" },
  { value: "Belgian", label: "Belgian" },
  { value: "Belizean", label: "Belizean" },
  { value: "Beninese", label: "Beninese" },
  { value: "Bhutanese", label: "Bhutanese" },
  { value: "Bolivian", label: "Bolivian" },
  { value: "Bosnian", label: "Bosnian" },
  { value: "Botswanan", label: "Botswanan" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "British", label: "British" },
  { value: "Bruneian", label: "Bruneian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Burkinabé", label: "Burkinabé" },
  { value: "Burmese", label: "Burmese" },
  { value: "Burundian", label: "Burundian" },
  { value: "Cabo Verdean", label: "Cabo Verdean" },
  { value: "Cambodian", label: "Cambodian" },
  { value: "Cameroonian", label: "Cameroonian" },
  { value: "Canadian", label: "Canadian" },
  { value: "Central African", label: "Central African" },
  { value: "Chadian", label: "Chadian" },
  { value: "Chilean", label: "Chilean" },
  { value: "Chinese", label: "Chinese" },
  { value: "Colombian", label: "Colombian" },
  { value: "Comoran", label: "Comoran" },
  { value: "Congolese", label: "Congolese" },
  { value: "Costa Rican", label: "Costa Rican" },
  { value: "Croatian", label: "Croatian" },
  { value: "Cuban", label: "Cuban" },
  { value: "Cypriot", label: "Cypriot" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Djiboutian", label: "Djiboutian" },
  { value: "Dominican", label: "Dominican" },
  { value: "Dutch", label: "Dutch" },
  { value: "East Timorese", label: "East Timorese" },
  { value: "Ecuadorian", label: "Ecuadorian" },
  { value: "Egyptian", label: "Egyptian" },
  { value: "Emirati", label: "Emirati" },
  { value: "English", label: "English" },
  { value: "Equatoguinean", label: "Equatoguinean" },
  { value: "Eritrean", label: "Eritrean" },
  { value: "Estonian", label: "Estonian" },
  { value: "Ethiopian", label: "Ethiopian" },
  { value: "Fijian", label: "Fijian" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },
  { value: "Gabonese", label: "Gabonese" },
  { value: "Gambian", label: "Gambian" },
  { value: "Georgian", label: "Georgian" },
  { value: "German", label: "German" },
  { value: "Ghanaian", label: "Ghanaian" },
  { value: "Greek", label: "Greek" },
  { value: "Grenadian", label: "Grenadian" },
  { value: "Guatemalan", label: "Guatemalan" },
  { value: "Guinean", label: "Guinean" },
  { value: "Bissau-Guinean", label: "Bissau-Guinean" },
  { value: "Guyanese", label: "Guyanese" },
  { value: "Haitian", label: "Haitian" },
  { value: "Honduran", label: "Honduran" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "Icelander", label: "Icelander" },
  { value: "Indian", label: "Indian" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Iranian", label: "Iranian" },
  { value: "Iraqi", label: "Iraqi" },
  { value: "Irish", label: "Irish" },
  { value: "Israeli", label: "Israeli" },
  { value: "Italian", label: "Italian" },
  { value: "Ivorian", label: "Ivorian" },
  { value: "Jamaican", label: "Jamaican" },
  { value: "Japanese", label: "Japanese" },
  { value: "Jordanian", label: "Jordanian" },
  { value: "Kazakhstani", label: "Kazakhstani" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "Kittitian", label: "Kittitian" },
  { value: "Kosovar", label: "Kosovar" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Kyrgyzstani", label: "Kyrgyzstani" },
  { value: "Lao", label: "Lao" },
  { value: "Latvian", label: "Latvian" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Liberian", label: "Liberian" },
  { value: "Libyan", label: "Libyan" },
  { value: "Liechtensteiner", label: "Liechtensteiner" },
  { value: "Lithuanian", label: "Lithuanian" },
  { value: "Luxembourger", label: "Luxembourger" },
  { value: "Macedonian", label: "Macedonian" },
  { value: "Malagasy", label: "Malagasy" },
  { value: "Malawian", label: "Malawian" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Maldivian", label: "Maldivian" },
  { value: "Malian", label: "Malian" },
  { value: "Maltese", label: "Maltese" },
  { value: "Marshallese", label: "Marshallese" },
  { value: "Mauritanian", label: "Mauritanian" },
  { value: "Mauritian", label: "Mauritian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Micronesian", label: "Micronesian" },
  { value: "Moldovan", label: "Moldovan" },
  { value: "Monacan", label: "Monacan" },
  { value: "Mongolian", label: "Mongolian" },
  { value: "Montenegrin", label: "Montenegrin" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Mozambican", label: "Mozambican" },
  { value: "Namibian", label: "Namibian" },
  { value: "Nauruan", label: "Nauruan" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "New Zealander", label: "New Zealander" },
  { value: "Nicaraguan", label: "Nicaraguan" },
  { value: "Nigerien", label: "Nigerien" },
  { value: "Nigerian", label: "Nigerian" },
  { value: "Ni-Vanuatu", label: "Ni-Vanuatu" },
  { value: "North Korean", label: "North Korean" },
  { value: "Norwegian", label: "Norwegian" },
  { value: "Omani", label: "Omani" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Palauan", label: "Palauan" },
  { value: "Palestinian", label: "Palestinian" },
  { value: "Panamanian", label: "Panamanian" },
  { value: "Papua New Guinean", label: "Papua New Guinean" },
  { value: "Paraguayan", label: "Paraguayan" },
  { value: "Peruvian", label: "Peruvian" },
  { value: "Filipino", label: "Filipino" },
  { value: "Polish", label: "Polish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Qatari", label: "Qatari" },
  { value: "Romanian", label: "Romanian" },
  { value: "Russian", label: "Russian" },
  { value: "Rwandan", label: "Rwandan" },
  { value: "Saint Lucian", label: "Saint Lucian" },
  { value: "Salvadoran", label: "Salvadoran" },
  { value: "Sammarinese", label: "Sammarinese" },
  { value: "Samoan", label: "Samoan" },
  { value: "São Toméan", label: "São Toméan" },
  { value: "Saudi", label: "Saudi" },
  { value: "Scottish", label: "Scottish" },
  { value: "Senegalese", label: "Senegalese" },
  { value: "Serbian", label: "Serbian" },
  { value: "Seychellois", label: "Seychellois" },
  { value: "Sierra Leonean", label: "Sierra Leonean" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "Slovak", label: "Slovak" },
  { value: "Slovene", label: "Slovene" },
  { value: "Solomon Islander", label: "Solomon Islander" },
  { value: "Somali", label: "Somali" },
  { value: "South African", label: "South African" },
  { value: "South Korean", label: "South Korean" },
  { value: "South Sudanese", label: "South Sudanese" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Sudanese", label: "Sudanese" },
  { value: "Surinamese", label: "Surinamese" },
  { value: "Swazi", label: "Swazi" },
  { value: "Swedish", label: "Swedish" },
  { value: "Swiss", label: "Swiss" },
  { value: "Syrian", label: "Syrian" },
  { value: "Tajikistani", label: "Tajikistani" },
  { value: "Tanzanian", label: "Tanzanian" },
  { value: "Thai", label: "Thai" },
  { value: "Togolese", label: "Togolese" },
  { value: "Tongan", label: "Tongan" },
  { value: "Trinidadian", label: "Trinidadian" },
  { value: "Tunisian", label: "Tunisian" },
  { value: "Turkish", label: "Turkish" },
  { value: "Turkmen", label: "Turkmen" },
  { value: "Tuvaluan", label: "Tuvaluan" },
  { value: "Ugandan", label: "Ugandan" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Uruguayan", label: "Uruguayan" },
  { value: "Uzbekistani", label: "Uzbekistani" },
  { value: "Vatican", label: "Vatican" },
  { value: "Venezuelan", label: "Venezuelan" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Vincentian", label: "Vincentian" },
  { value: "Welsh", label: "Welsh" },
  { value: "Yemeni", label: "Yemeni" },
  { value: "Zambian", label: "Zambian" },
  { value: "Zimbabwean", label: "Zimbabwean" },
];
