# Generated by Django 5.2 on 2026-08-15 15:58

import Content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=Content.models.content_image_storage, upload_to='blog/covers/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=Content.models.content_image_storage, upload_to='testimonials/'),
        ),
    ]
