# Generated by Django 5.2 on 2026-08-16 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_alter_blogpost_cover_image_alter_testimonial_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-created_at'], name='blog_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_active', '-created_at'], name='testimonial_active_idx'),
        ),
    ]
