# Generated by Django 5.2 on 2026-08-10 07:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expert_Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='cv_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchexperience',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('company', 'Company User'), ('admin', 'Admin'), ('content_manager', 'Content_Manager')], default='company', max_length=20),
        ),
    ]
