# Generated by Django 5.2 on 2026-08-15 15:34

import Expert_Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expert_Registration', '0002_expert_code_alter_expert_cv_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='cv_file',
            field=models.FileField(blank=True, null=True, storage=Expert_Registration.models.cv_storage, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
