# Generated by Django 5.2 on 2026-08-16 07:52

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expert_Registration', '0004_accessrequest'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Must come first: the gin_trgm_ops indexes below cannot be created
        # until pg_trgm exists. Creating the extension needs a superuser or a
        # role with CREATE privilege on the database; on a managed instance
        # where that is not available, enable pg_trgm once by hand and this
        # becomes a no-op (CREATE EXTENSION IF NOT EXISTS).
        TrigramExtension(),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['requested_by', 'expert', 'status'], name='accessreq_user_expert_status'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['status', '-created_at'], name='accessreq_status_created'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['expert'], name='accessreq_expert_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalbackground',
            index=models.Index(fields=['expert', '-year_of_grad'], name='edu_expert_grad_idx'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=models.Index(fields=['registered_by', '-created_at'], name='expert_regby_created_idx'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=models.Index(fields=['-created_at'], name='expert_created_idx'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=models.Index(fields=['-updated_at'], name='expert_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=models.Index(fields=['is_deleted', '-created_at'], name='expert_deleted_created_idx'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=django.contrib.postgres.indexes.GinIndex(fields=['key_words'], name='expert_keywords_gin'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=django.contrib.postgres.indexes.GinIndex(fields=['resume_text'], name='expert_resume_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=django.contrib.postgres.indexes.GinIndex(fields=['expertise_area'], name='expert_expertise_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='researchexperience',
            index=django.contrib.postgres.indexes.GinIndex(fields=['client'], name='research_client_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='researchexperience',
            index=django.contrib.postgres.indexes.GinIndex(fields=['project_name'], name='research_project_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company_name'], name='user_company_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['expert', '-start_date'], name='work_expert_start_idx'),
        ),
    ]
